// src/components/agent/MultiAgentWindowButton.tsx
import { Sparkles } from "lucide-react";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { useHasAgentApiKey } from "@/hooks/useHasAgentApiKey";
import { cn } from "@/lib/utils";
import { openMultiAgentWindow } from "@/services/window/multiAgentWindow";
import { toUserMessage } from "@/types/error";

interface MultiAgentWindowButtonProps {
  label: string;
  className?: string;
  iconClassName?: string;
  tooltipSide?: "top" | "right" | "bottom" | "left";
}

/** 打开或聚焦多仓鲸灵单例窗口。 */
export function MultiAgentWindowButton({
  label,
  className,
  iconClassName,
  tooltipSide = "top",
}: MultiAgentWindowButtonProps) {
  const { t } = useTranslation();
  const hasApiKey = useHasAgentApiKey();
  const accessibleLabel = hasApiKey ? label : t("common.aiApiKeyRequired");

  async function handleOpen(): Promise<void> {
    if (!hasApiKey) {
      return;
    }
    try {
      await openMultiAgentWindow();
    } catch (error) {
      toast.error(toUserMessage(error) || t("multiAgent.openFailed"));
    }
  }

  return (
    <Tooltip delayDuration={300}>
      <TooltipTrigger asChild>
        <span className="inline-flex">
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className={cn("text-muted-foreground", className)}
            aria-label={accessibleLabel}
            disabled={!hasApiKey}
            onClick={() => {
              void handleOpen();
            }}
          >
            <Sparkles className={iconClassName} aria-hidden="true" />
          </Button>
        </span>
      </TooltipTrigger>
      <TooltipContent side={tooltipSide}>{accessibleLabel}</TooltipContent>
    </Tooltip>
  );
}

// src/components/Agent/src/MultiAgentWindowButton.vue
<script setup lang="ts">
import { computed } from "vue";

import { Button, Tooltip, message } from "antdv-next";
import { useI18n } from "vue-i18n";

import { Icon } from "@/components/Icon";
import { useHasAgentApiKey } from "@/hooks/core/useHasAgentApiKey";
import { cn } from "@/lib/utils";
import { openMultiAgentWindow } from "@/services/window/multiAgentWindow";
import { toUserMessage } from "@/types/error";

defineOptions({ name: "MultiAgentWindowButton" });

const props = withDefaults(
  defineProps<{
    label: string;
    className?: string;
    iconClassName?: string;
    tooltipSide?: "top" | "right" | "bottom" | "left";
  }>(),
  { className: "", iconClassName: "", tooltipSide: "top" },
);

const { t } = useI18n();
const hasApiKey = useHasAgentApiKey();
const accessibleLabel = computed(() =>
  hasApiKey.value ? props.label : t("common.aiApiKeyRequired"),
);

async function handleOpen(): Promise<void> {
  if (!hasApiKey.value) {
    return;
  }
  try {
    await openMultiAgentWindow();
  } catch (error) {
    message.error(toUserMessage(error) || t("multiAgent.openFailed"));
  }
}
</script>

<template>
  <Tooltip :title="accessibleLabel" :placement="tooltipSide">
    <Button
      type="text"
      size="small"
      :class="cn('text-muted-foreground', className)"
      :aria-label="accessibleLabel"
      :disabled="!hasApiKey"
      @click="void handleOpen()"
    >
      <Icon name="Sparkles" :class="iconClassName" :size="14" />
    </Button>
  </Tooltip>
</template>
