// src/components/project/ProjectContextMenu.tsx
import { useState, type ReactElement } from "react";
import { useTranslation } from "react-i18next";
import {
  Copy,
  ExternalLink,
  FolderOpen,
  Globe,
  Link,
  SquarePen,
  Terminal,
  Trash2,
} from "lucide-react";
import { toast } from "sonner";

import { ContextMenuSubTrigger } from "@/components/common/ContextMenuSubTrigger";
import { ProjectSettingsDialog } from "@/components/project/ProjectSettingsDialog";
import { AppAlertDialogContent } from "@/components/common/AppDialogContent";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuSeparator,
  ContextMenuSub,
  ContextMenuSubContent,
  ContextMenuTrigger,
} from "@/components/ui/context-menu";

import { gitService, openPrimaryRemoteInBrowser, pickPrimaryRemoteUrl } from "@/services/git";
import { systemOpenService } from "@/services/system/system.open";
import { detectAppOs } from "@/services/window/windowChrome";
import { useProjectStore } from "@/store/useProjectStore";

import { toUserMessage } from "@/types/error";
import type { Project } from "@/types/project";
import { copyToClipboard } from "@/utils/clipboard";
import { useContextMenuOpen, withContextMenuHighlight } from "@/utils/contextMenuHighlight";
import { deferUi } from "@/utils/deferUi";
import { revealInFileManagerLabel } from "@/utils/platformLabels";

interface ProjectContextMenuProps {
  project: Project;
  onOpenProject: (projectId: string) => void;
  disabled?: boolean;
  /** 菜单打开时选中该项 */
  onMenuOpen?: () => void;
  /** 从应用移除成功后回调 */
  onRemoved?: () => void;
  children: ReactElement;
}

/** 最近与分组列表共用的仓库右键操作。 */
export function ProjectContextMenu({
  project,
  onOpenProject,
  disabled = false,
  onMenuOpen,
  onRemoved,
  children,
}: ProjectContextMenuProps) {
  const { t } = useTranslation();
  const removeProject = useProjectStore((state) => state.removeProject);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const { menuOpen, onOpenChange } = useContextMenuOpen(onMenuOpen);
  const revealLabel = revealInFileManagerLabel(detectAppOs(), t);

  async function handleCopyRemote(): Promise<void> {
    try {
      const remoteUrl = pickPrimaryRemoteUrl(await gitService.listRemotes(project.path));
      if (!remoteUrl) {
        toast.message(t("repo.tabCopyRemoteEmpty"));
        return;
      }
      await copyToClipboard(remoteUrl);
      toast.success(t("repo.tabCopyRemoteSuccess"));
    } catch (error) {
      toast.error(toUserMessage(error));
    }
  }

  async function handleCopyPath(): Promise<void> {
    try {
      await copyToClipboard(project.path);
      toast.success(t("repo.tabCopyPathSuccess"));
    } catch (error) {
      toast.error(toUserMessage(error));
    }
  }

  async function runSystemOpen(action: () => Promise<void>): Promise<void> {
    try {
      await action();
    } catch (error) {
      toast.error(toUserMessage(error));
    }
  }

  async function handleOpenRemoteInBrowser(): Promise<void> {
    try {
      const result = await openPrimaryRemoteInBrowser(project.path);
      if (result === "empty") {
        toast.message(t("repo.tabCopyRemoteEmpty"));
        return;
      }
      if (result === "unsupported") {
        toast.error(t("repo.openRemoteUnsupported"));
        return;
      }
    } catch (error) {
      toast.error(toUserMessage(error));
    }
  }

  async function handleDelete(): Promise<void> {
    if (deleting) {
      return;
    }
    setDeleting(true);
    try {
      await removeProject(project.id);
      toast.success(t("projectManager.deleteProjectSuccess", { name: project.name }));
      setDeleteOpen(false);
      onRemoved?.();
    } catch (error) {
      toast.error(toUserMessage(error));
    } finally {
      setDeleting(false);
    }
  }

  return (
    <>
      <ContextMenu onOpenChange={onOpenChange}>
        <ContextMenuTrigger asChild>
          {withContextMenuHighlight(children, menuOpen)}
        </ContextMenuTrigger>
        <ContextMenuContent className="min-w-48">
          <ContextMenuItem disabled={disabled} onSelect={() => onOpenProject(project.id)}>
            <FolderOpen aria-hidden="true" />
            {t("projectManager.openProject")}
          </ContextMenuItem>
          <ContextMenuItem
            disabled={disabled}
            onSelect={() => deferUi(() => setSettingsOpen(true))}
          >
            <SquarePen aria-hidden="true" />
            {t("projectManager.manageEditAction")}
          </ContextMenuItem>
          <ContextMenuSeparator />
          {/* 复制类操作有共性，收进子菜单 */}
          <ContextMenuSub>
            <ContextMenuSubTrigger disabled={disabled}>
              <Copy aria-hidden="true" />
              {t("common.copy")}
            </ContextMenuSubTrigger>
            <ContextMenuSubContent className="min-w-44">
              <ContextMenuItem disabled={disabled} onSelect={() => void handleCopyRemote()}>
                <Link aria-hidden="true" />
                {t("projectManager.copyRemote")}
              </ContextMenuItem>
              <ContextMenuItem disabled={disabled} onSelect={() => void handleCopyPath()}>
                <Copy aria-hidden="true" />
                {t("projectManager.copyLocalPath")}
              </ContextMenuItem>
            </ContextMenuSubContent>
          </ContextMenuSub>
          <ContextMenuSeparator />
          {/* 系统打开：收入「打开方式」子菜单（见 ui-guidelines §2.3） */}
          <ContextMenuSub>
            <ContextMenuSubTrigger disabled={disabled}>
              <ExternalLink aria-hidden="true" />
              {t("repo.openVia")}
            </ContextMenuSubTrigger>
            <ContextMenuSubContent className="min-w-44">
              <ContextMenuItem
                disabled={disabled}
                onSelect={() =>
                  void runSystemOpen(() => systemOpenService.revealInFileManager(project.path))
                }
              >
                <FolderOpen aria-hidden="true" />
                {revealLabel}
              </ContextMenuItem>
              <ContextMenuItem
                disabled={disabled}
                onSelect={() =>
                  void runSystemOpen(() => systemOpenService.openInEditor(project.path))
                }
              >
                <ExternalLink aria-hidden="true" />
                {t("repo.openInEditor")}
              </ContextMenuItem>
              <ContextMenuItem
                disabled={disabled}
                onSelect={() =>
                  void runSystemOpen(() => systemOpenService.openTerminal(project.path))
                }
              >
                <Terminal aria-hidden="true" />
                {t("repo.openInTerminal")}
              </ContextMenuItem>
              <ContextMenuItem
                disabled={disabled}
                onSelect={() => void handleOpenRemoteInBrowser()}
              >
                <Globe aria-hidden="true" />
                {t("repo.openRemoteInBrowser")}
              </ContextMenuItem>
            </ContextMenuSubContent>
          </ContextMenuSub>
          <ContextMenuSeparator />
          <ContextMenuItem
            variant="destructive"
            disabled={disabled}
            onSelect={() => deferUi(() => setDeleteOpen(true))}
          >
            <Trash2 aria-hidden="true" />
            {t("projectManager.deleteProject")}
          </ContextMenuItem>
        </ContextMenuContent>
      </ContextMenu>

      <ProjectSettingsDialog project={project} open={settingsOpen} onOpenChange={setSettingsOpen} />

      <AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}>
        <AppAlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t("projectManager.deleteProjectTitle")}</AlertDialogTitle>
            <AlertDialogDescription>
              {t("projectManager.deleteProjectQuestion", { name: project.name })}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={deleting}>{t("common.cancel")}</AlertDialogCancel>
            <AlertDialogAction
              variant="destructive"
              disabled={deleting}
              onClick={(event) => {
                event.preventDefault();
                void handleDelete();
              }}
            >
              {deleting ? t("common.loading") : t("projectManager.deleteProject")}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AppAlertDialogContent>
      </AlertDialog>
    </>
  );
}

// src/components/Project/src/ProjectContextMenu.vue
<script setup lang="ts">
import { computed, ref } from "vue";

import { Dropdown, Modal, message, type MenuProps } from "antdv-next";
import { useI18n } from "vue-i18n";

import ProjectSettingsDialog from "./ProjectSettingsDialog.vue";
import { gitService, openPrimaryRemoteInBrowser, pickPrimaryRemoteUrl } from "@/services/git";
import { systemOpenService } from "@/services/system/system.open";
import { detectAppOs } from "@/services/window/windowChrome";
import { useProjectStoreWithOut } from "@/store/modules/project";
import { toUserMessage } from "@/types/error";
import type { Project } from "@/types/project";
import { copyToClipboard } from "@/utils/clipboard";

defineOptions({ name: "ProjectContextMenu" });

const props = withDefaults(
  defineProps<{
    project: Project;
    disabled?: boolean;
  }>(),
  { disabled: false },
);

const emit = defineEmits<{
  open: [projectId: string];
  menuOpen: [];
  removed: [];
}>();

const { t } = useI18n();
const settingsOpen = ref(false);
const deleteOpen = ref(false);
const deleting = ref(false);

const revealLabel = computed(() => {
  const os = detectAppOs();
  if (os === "windows") {
    return t("repo.openInExplorer");
  }
  if (os === "linux") {
    return t("repo.openInFileManager");
  }
  return t("repo.openInFinder");
});

const menuItems = computed<MenuProps["items"]>(() => [
  { key: "open", label: t("projectManager.openProject"), disabled: props.disabled },
  { key: "edit", label: t("projectManager.manageEditAction"), disabled: props.disabled },
  { type: "divider" },
  {
    key: "copy",
    label: t("common.copy"),
    disabled: props.disabled,
    children: [
      { key: "copy-remote", label: t("projectManager.copyRemote") },
      { key: "copy-path", label: t("projectManager.copyLocalPath") },
    ],
  },
  {
    key: "open-via",
    label: t("repo.openVia"),
    disabled: props.disabled,
    children: [
      { key: "open-folder", label: revealLabel.value },
      { key: "open-editor", label: t("repo.openInEditor") },
      { key: "open-terminal", label: t("repo.openInTerminal") },
      { key: "open-browser", label: t("repo.openRemoteInBrowser") },
    ],
  },
  { type: "divider" },
  {
    key: "delete",
    label: t("projectManager.deleteProject"),
    danger: true,
    disabled: props.disabled,
  },
]);

async function handleCopyRemote(): Promise<void> {
  try {
    const remoteUrl = pickPrimaryRemoteUrl(await gitService.listRemotes(props.project.path));
    if (!remoteUrl) {
      message.info(t("repo.tabCopyRemoteEmpty"));
      return;
    }
    await copyToClipboard(remoteUrl);
    message.success(t("repo.tabCopyRemoteSuccess"));
  } catch (error) {
    message.error(toUserMessage(error));
  }
}

async function handleCopyPath(): Promise<void> {
  try {
    await copyToClipboard(props.project.path);
    message.success(t("repo.tabCopyPathSuccess"));
  } catch (error) {
    message.error(toUserMessage(error));
  }
}

async function runSystemOpen(action: () => Promise<void>): Promise<void> {
  try {
    await action();
  } catch (error) {
    message.error(toUserMessage(error));
  }
}

async function handleOpenRemoteInBrowser(): Promise<void> {
  try {
    const result = await openPrimaryRemoteInBrowser(props.project.path);
    if (result === "empty") {
      message.info(t("repo.tabCopyRemoteEmpty"));
      return;
    }
    if (result === "unsupported") {
      message.error(t("repo.openRemoteUnsupported"));
    }
  } catch (error) {
    message.error(toUserMessage(error));
  }
}

async function handleDelete(): Promise<void> {
  if (deleting.value) {
    return;
  }
  deleting.value = true;
  try {
    await useProjectStoreWithOut().removeProject(props.project.id);
    message.success(t("projectManager.deleteProjectSuccess", { name: props.project.name }));
    deleteOpen.value = false;
    emit("removed");
  } catch (error) {
    message.error(toUserMessage(error));
  } finally {
    deleting.value = false;
  }
}

const handleMenuClick: MenuProps["onClick"] = ({ key }) => {
  if (key === "open") {
    emit("open", props.project.id);
    return;
  }
  if (key === "edit") {
    settingsOpen.value = true;
    return;
  }
  if (key === "copy-remote") {
    void handleCopyRemote();
    return;
  }
  if (key === "copy-path") {
    void handleCopyPath();
    return;
  }
  if (key === "open-folder") {
    void runSystemOpen(() => systemOpenService.revealInFileManager(props.project.path));
    return;
  }
  if (key === "open-editor") {
    void runSystemOpen(() => systemOpenService.openInEditor(props.project.path));
    return;
  }
  if (key === "open-terminal") {
    void runSystemOpen(() => systemOpenService.openTerminal(props.project.path));
    return;
  }
  if (key === "open-browser") {
    void handleOpenRemoteInBrowser();
    return;
  }
  if (key === "delete") {
    deleteOpen.value = true;
  }
};

function handleOpenChange(open: boolean): void {
  if (open) {
    emit("menuOpen");
  }
}
</script>

<template>
  <Dropdown
    :trigger="['contextmenu']"
    :disabled="disabled"
    :menu="{ items: menuItems, onClick: handleMenuClick }"
    @open-change="handleOpenChange"
  >
    <slot />
  </Dropdown>

  <ProjectSettingsDialog
    v-if="settingsOpen"
    :project="project"
    :open="settingsOpen"
    @update:open="(next: boolean) => (settingsOpen = next)"
  />

  <Modal
    :open="deleteOpen"
    :title="t('projectManager.deleteProjectTitle')"
    :ok-text="t('projectManager.deleteProject')"
    :cancel-text="t('common.cancel')"
    ok-type="danger"
    :confirm-loading="deleting"
    @update:open="(next: boolean) => (deleteOpen = next)"
    @ok="void handleDelete()"
  >
    <p class="text-sm">
      {{ t("projectManager.deleteProjectQuestion", { name: project.name }) }}
    </p>
  </Modal>
</template>
