// src/components/project/RecentProjectList.tsx
import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { FolderGit2, Search } from "lucide-react";

import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { RemoteRepositoryLabel } from "@/components/project/RemoteRepositoryLabel";
import { cn } from "@/lib/utils";

import { gitService, pickPrimaryRemoteUrl } from "@/services/git";
import { openExternalUrl } from "@/services/system/open-url";
import { useProjectStore } from "@/store/useProjectStore";

import { Project, RecentItem } from "@/types/project";
import { parseRemoteRepository } from "@/utils/remoteRepository";

interface RecentProjectRow {
  id: string;
  name: string;
  path: string;
  lastOpenedAt: string | null;
}

function mergeRecentProjects(recent: RecentItem[], projects: Project[]): RecentProjectRow[] {
  const projectById = new Map(projects.map((project) => [project.id, project]));

  return recent.flatMap((item) => {
    const project = projectById.get(item.projectId);
    if (!project) {
      return [];
    }

    return [
      {
        id: project.id,
        name: project.name,
        path: project.path,
        lastOpenedAt: item.openedAt || project.lastOpenedAt,
      },
    ];
  });
}

interface RecentProjectListProps {
  onOpenProject: (projectId: string) => void;
}

/** 最近项目列表：单击选中，双击进入仓库 */
export function RecentProjectList({
  onOpenProject,
}: RecentProjectListProps) {
  const { t } = useTranslation();
  const projects = useProjectStore((state) => state.projects);
  const recent = useProjectStore((state) => state.recent);
  const loading = useProjectStore((state) => state.loading);

  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [hoveredId, setHoveredId] = useState<string | null>(null);
  const [filter, setFilter] = useState("");
  const [remoteUrls, setRemoteUrls] = useState<Record<string, string | null>>({});

  const rows = useMemo(() => mergeRecentProjects(recent, projects), [projects, recent]);
  const filteredRows = useMemo(() => {
    const query = filter.trim().toLowerCase();
    return query ? rows.filter((item) => item.name.toLowerCase().includes(query) || item.path.toLowerCase().includes(query)) : rows;
  }, [filter, rows]);

  function handleOpenProject(id: string): void {
    setSelectedId(id);
    onOpenProject(id);
  }

  async function showRemoteUrl(project: RecentProjectRow): Promise<void> {
    setHoveredId(project.id);
    if (project.id in remoteUrls) {
      return;
    }

    try {
      const remotes = await gitService.listRemotes(project.path);
      setRemoteUrls((current) => ({
        ...current,
        [project.id]: pickPrimaryRemoteUrl(remotes),
      }));
    } catch (error) {
      console.warn("读取仓库远程地址失败", error);
      setRemoteUrls((current) => ({ ...current, [project.id]: null }));
    }
  }

  async function openRemoteUrl(url: string): Promise<void> {
    try {
      await openExternalUrl(url);
    } catch (error) {
      console.warn("打开仓库远程地址失败", error);
    }
  }

  if (rows.length === 0) {
    return (
      <div className="flex flex-1 flex-col items-center justify-center px-6 py-16 text-center">
        <div className="bg-muted flex size-14 items-center justify-center rounded-2xl">
          <FolderGit2 className="text-muted-foreground size-7" aria-hidden="true" />
        </div>
        <h2 className="mt-5 text-lg font-semibold">{t("dashboard.recentEmptyTitle")}</h2>
        <p className="text-muted-foreground mt-2 max-w-sm text-sm">
          {loading ? t("common.loading") : t("dashboard.recentEmptyDescription")}
        </p>
      </div>
    );
  }

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <div className="flex shrink-0 items-start justify-between gap-4 pb-4">
        <div>
          <div className="flex items-center gap-2"><h2 className="text-sm font-semibold">{t("dashboard.recentTitle")}</h2><Badge variant="secondary" className="px-1.5 py-0 text-[10px] tabular-nums">{t("dashboard.recentCount", { count: rows.length })}</Badge></div>
          <p className="text-muted-foreground mt-0.5 text-xs">{t("dashboard.recentDescription")}</p>
        </div>
        <label className="relative block w-52"><Search className="text-muted-foreground pointer-events-none absolute top-1/2 left-2.5 size-3.5 -translate-y-1/2" aria-hidden="true" /><input value={filter} onChange={(event) => setFilter(event.target.value)} className="border-input bg-background focus-visible:ring-ring h-8 w-full rounded-md border pr-3 pl-8 text-xs outline-none focus-visible:ring-2" placeholder={t("repo.filter")} aria-label={t("repo.filter")} /></label>
      </div>

      <div className="min-h-0 flex-1">
        <ScrollArea className="h-full pb-4 [&_[data-slot=scroll-area-viewport]>div]:!block [&_[data-slot=scroll-area-viewport]>div]:pr-2">
          <ul className="space-y-1" role="listbox" aria-label={t("dashboard.recentTitle")}>
            {filteredRows.map((project) => {
              const isSelected = selectedId === project.id;
              const remoteUrl = remoteUrls[project.id];
              const remote = remoteUrl
                ? parseRemoteRepository(remoteUrl)
                : null;

              return (
                <li key={project.id} role="option" aria-selected={isSelected}>
                  <button
                        type="button"
                        className={cn(
                          // 勿加 overflow-hidden，否则会裁掉右侧圆角（看起来左右不一致）
                          "focus-visible:ring-ring group relative flex w-full min-w-0 items-center gap-3 rounded-md px-3 py-3 text-left transition-colors focus-visible:ring-2 focus-visible:outline-none",
                          isSelected
                            ? "bg-accent hover:bg-accent"
                            : "hover:bg-accent/60",
                        )}
                        onClick={() => {
                          setSelectedId(project.id);
                        }}
                        onDoubleClick={() => {
                          handleOpenProject(project.id);
                        }}
                        onMouseEnter={() => void showRemoteUrl(project)}
                        onMouseLeave={() => setHoveredId(null)}
                        onFocus={() => void showRemoteUrl(project)}
                        onBlur={() => setHoveredId(null)}
                        onKeyDown={(event) => {
                          if (event.key === "Enter" && isSelected) {
                            event.preventDefault();
                            handleOpenProject(project.id);
                          }
                        }}
                      >
                    <span
                      className="text-muted-foreground bg-muted group-hover:bg-muted-foreground/10 group-focus-visible:bg-muted-foreground/10 flex size-9 shrink-0 items-center justify-center rounded-md transition-colors"
                    >
                      <FolderGit2 className="size-4" aria-hidden="true" />
                    </span>
                    <span className="min-w-0 flex-1">
                      <span className="flex min-w-0 items-center gap-2">
                        <span className="truncate text-sm font-medium">{project.name}</span>
                        {hoveredId === project.id && remote ? (
                          <RemoteRepositoryLabel
                            remote={remote}
                            onOpen={(url) => void openRemoteUrl(url)}
                          />
                        ) : null}
                      </span>
                      <span className="text-muted-foreground mt-0.5 block truncate text-xs">
                        {project.path}
                      </span>
                    </span>
                  </button>
                </li>
              );
            })}
          </ul>
        </ScrollArea>
      </div>
    </div>
  );
}

// src/views/dashboard/components/RecentProjectList.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";
import { storeToRefs } from "pinia";

import { Card, Dropdown, Empty, Input, Listy, Spin, Tag, Tooltip, Typography } from "antdv-next";
import { useClipboard } from "@vueuse/core";
import { useI18n } from "vue-i18n";

import { Icon } from "@/components/Icon";

import { useMessage } from "@/hooks/web/useMessage";
import { useProjectMenu } from "@/hooks/web/useProjectMenu";

import { useProjectStore } from "@/store/modules/project";

import { parseRemoteRepository, type RemoteRepository } from "@/utils/remoteRepository";

import type { Project } from "@/types/project";

defineOptions({ name: "RecentProjectList" });

interface RecentListRow {
  project: Project;
  remote: RemoteRepository | null;
}

const emit = defineEmits<{
  open: [projectId: string];
}>();

const { t } = useI18n();
const message = useMessage();
const { copy } = useClipboard({ legacy: true });
const projectStore = useProjectStore();
const { recentProjects: rows } = storeToRefs(projectStore);
const filter = ref("");
const loading = ref(false);
const { menuItems, handleMenuClick } = useProjectMenu({
  onOpen: (projectId) => emit("open", projectId),
  deleteMode: "recent",
});

/** 解析主远端，列表右侧展示可复制的仓库名 */
function remoteOf(project: Project) {
  const remoteUrl = project.remoteUrl?.trim();
  return remoteUrl ? parseRemoteRepository(remoteUrl) : null;
}

const filteredRows = computed(() => {
  const query = filter.value.trim().toLowerCase();
  const source = query
    ? rows.value.filter(
        (item) =>
          item.name.toLowerCase().includes(query) || item.path.toLowerCase().includes(query),
      )
    : rows.value;
  return source.map((project): RecentListRow => ({
    project,
    remote: remoteOf(project),
  }));
});

/** Listy 行键：项目 id */
function getRowKey(item: RecentListRow): string {
  return item.project.id;
}

let mounted = true;
onMounted(() => {
  loadRecentCatalog();
});
onUnmounted(() => {
  mounted = false;
});

/** 同时拉登记仓库和最近打开记录 */
async function loadRecentCatalog() {
  loading.value = true;
  try {
    await Promise.all([projectStore.loadProjects(), projectStore.loadRecent()]);
  } catch (error) {
    if (mounted) {
      message.error(error);
    }
  } finally {
    if (mounted) {
      loading.value = false;
    }
  }
}

/** 打开最近列表里的仓库 */
function handleOpenProject(id: string): void {
  emit("open", id);
}

/** 复制远端 URL */
async function copyRemoteUrl(url: string): Promise<void> {
  try {
    await copy(url);
    message.success(t("repo.copySuccess"));
  } catch (error) {
    message.error(error);
  }
}
</script>

<template>
  <Card>
    <template #title>
      <span class="inline-flex items-center gap-2">
        {{ t("dashboard.recentTitle") }}
        <Tag>{{ t("dashboard.recentCount", { count: rows.length }) }}</Tag>
      </span>
    </template>
    <template #extra>
      <Input v-model:value="filter" class="w-52" :placeholder="t('repo.filter')">
        <template #prefix>
          <Icon name="Search" :size="14" />
        </template>
      </Input>
    </template>

    <Spin :spinning="loading">
      <Empty v-if="filteredRows.length === 0" :description="t('common.empty')" />

      <Listy v-else :items="filteredRows" :row-key="getRowKey">
        <template #itemRender="{ project, remote }">
          <Dropdown
            :trigger="['contextmenu']"
            :menu="{ items: menuItems, onClick: handleMenuClick(project) }"
          >
            <button
              type="button"
              class="group relative flex! w-full min-w-0 items-center gap-3 px-3 py-3 text-left"
              @click="handleOpenProject(project.id)"
            >
              <span
                v-if="project.icon"
                class="bg-muted text-muted-foreground group-hover:bg-muted-foreground/10 flex size-9 shrink-0 items-center justify-center rounded-md transition-colors"
              >
                <Icon :name="project.icon" />
              </span>
              <span class="min-w-0 flex-1">
                <span class="flex min-w-0 items-center gap-2">
                  <Typography.Text class="min-w-0 flex-1 truncate" strong>
                    {{ project.name }}
                  </Typography.Text>
                  <Tooltip v-if="remote" :title="t('repo.copy')">
                    <Typography.Link
                      class="ml-auto inline-flex w-max max-w-[46%] min-w-0 shrink-0 items-center gap-1 font-mono text-xs"
                      :title="remote.url"
                      @click.stop.prevent="copyRemoteUrl(remote.url)"
                    >
                      <Icon name="GitFork" :size="14" class="shrink-0" />
                      <span class="truncate">{{ remote.repositoryName }}</span>
                    </Typography.Link>
                  </Tooltip>
                </span>
                <Typography.Text class="mt-0.5 block truncate text-xs" type="secondary">
                  {{ project.path }}
                </Typography.Text>
              </span>
            </button>
          </Dropdown>
        </template>
      </Listy>
    </Spin>
  </Card>
</template>
