// src/views/repo/components/ActivityBar.vue
<script setup lang="ts">
import { computed } from "vue";

import { Button, Tooltip } from "antdv-next";
import { useI18n } from "vue-i18n";

import { Icon } from "@/components/Icon";
import { useHasAgentApiKey } from "@/hooks/core/useHasAgentApiKey";
import { useSettingsDrawerStore } from "@/store/modules/setting";
import type { SidebarView } from "@/utils/activityBarOrder";

defineOptions({ name: "ActivityBar" });

const props = defineProps<{
  /** 当前侧栏视图 */
  active: SidebarView;
}>();

const emit = defineEmits<{
  change: [view: SidebarView];
}>();

const { t } = useI18n();
const hasApiKey = useHasAgentApiKey();
const settingsDrawerStore = useSettingsDrawerStore();

const items = computed(() => [
  { id: "files" as const, icon: "FolderTree", label: t("repo.fileTree") },
  { id: "branches" as const, icon: "GitBranch", label: t("repo.branches") },
  { id: "tags" as const, icon: "Tag", label: t("repo.tags") },
  { id: "agent" as const, icon: "Sparkles", label: t("agent.title") },
]);

function handleClick(id: SidebarView): void {
  if (id === "agent" && !hasApiKey.value) {
    return;
  }
  emit("change", id);
}
</script>

<template>
  <nav
    class="border-border bg-muted/30 flex w-11 shrink-0 flex-col items-center gap-1 border-r py-2"
  >
    <Tooltip v-for="item in items" :key="item.id" :title="item.label" placement="right">
      <Button
        size="small"
        class="size-8"
        :type="props.active === item.id ? 'primary' : 'text'"
        :ghost="props.active === item.id"
        :aria-pressed="props.active === item.id"
        :disabled="item.id === 'agent' && !hasApiKey"
        @click="handleClick(item.id)"
      >
        <template #icon>
          <Icon :name="item.icon" :size="16" />
        </template>
      </Button>
    </Tooltip>
    <div class="flex-1" />
    <Tooltip :title="t('repo.settings')" placement="right">
      <Button type="text" size="small" class="size-8" @click="settingsDrawerStore.openDrawer()">
        <template #icon>
          <Icon name="Settings" :size="16" />
        </template>
      </Button>
    </Tooltip>
  </nav>
</template>

// src/components/layout/ActivityBar.tsx
import { FolderTree, GitBranch, Settings, Sparkles, Tag, type LucideIcon } from "lucide-react";
import { useTranslation } from "react-i18next";

import { Button } from "@/components/ui/button";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { useHasAgentApiKey } from "@/hooks/useHasAgentApiKey";
import { cn } from "@/lib/utils";

import { useSettingsDrawerStore } from "@/store/useSettingsDrawerStore";

export type SidebarView = "files" | "branches" | "tags" | "agent";

interface ActivityBarProps {
  active: SidebarView;
  onChange: (view: SidebarView) => void;
}

interface ActivityItem {
  id: SidebarView;
  icon: LucideIcon;
  labelKey: "repo.fileTree" | "repo.branches" | "repo.tags" | "agent.title";
}

const ITEMS: ActivityItem[] = [
  { id: "files", icon: FolderTree, labelKey: "repo.fileTree" },
  { id: "branches", icon: GitBranch, labelKey: "repo.branches" },
  { id: "tags", icon: Tag, labelKey: "repo.tags" },
  { id: "agent", icon: Sparkles, labelKey: "agent.title" },
];

/** 左侧活动栏：切换目录树、分支或 Agent；底部为应用设置入口 */
export function ActivityBar({ active, onChange }: ActivityBarProps) {
  const { t } = useTranslation();
  const openDrawer = useSettingsDrawerStore((state) => state.openDrawer);
  const settingsOpen = useSettingsDrawerStore((state) => state.open);
  const hasApiKey = useHasAgentApiKey();

  return (
    <nav
      className="border-border bg-muted/30 flex w-11 shrink-0 flex-col items-center gap-1 border-r py-2"
      aria-label={t("repo.activityBar")}
    >
      {ITEMS.map((item) => {
        const Icon = item.icon;
        const isActive = item.id === active;
        const label = t(item.labelKey);
        const agentLocked = item.id === "agent" && !hasApiKey;
        const tip = agentLocked ? t("common.aiApiKeyRequired") : label;

        return (
          <Tooltip key={item.id} delayDuration={300}>
            <TooltipTrigger asChild>
              <span className="inline-flex">
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  className={cn(
                    "size-8 transition-colors",
                    isActive
                      ? "bg-primary/10 text-primary hover:bg-primary/15 hover:text-primary"
                      : "text-muted-foreground",
                  )}
                  aria-label={tip}
                  aria-pressed={isActive}
                  disabled={agentLocked}
                  onClick={() => onChange(item.id)}
                >
                  <Icon className="size-4" aria-hidden="true" />
                </Button>
              </span>
            </TooltipTrigger>
            <TooltipContent side="right" sideOffset={8}>
              {tip}
            </TooltipContent>
          </Tooltip>
        );
      })}

      <div className="mt-auto flex flex-col items-center">
        <Tooltip delayDuration={300}>
          <TooltipTrigger asChild>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className={cn(
                "size-8",
                settingsOpen
                  ? "bg-primary/10 text-primary hover:bg-primary/15 hover:text-primary"
                  : "text-muted-foreground",
              )}
              aria-label={t("repo.settings")}
              aria-pressed={settingsOpen}
              onClick={() => openDrawer()}
            >
              <Settings className="size-4" aria-hidden="true" />
            </Button>
          </TooltipTrigger>
          <TooltipContent side="right" sideOffset={8}>
            {t("repo.settings")}
          </TooltipContent>
        </Tooltip>
      </div>
    </nav>
  );
}
