// src/views/repo/components/RepoWorkspaceLayout.vue
<script setup lang="ts">
import ActivityBar from "./ActivityBar.vue";
import RepoToolbar from "./RepoToolbar.vue";
import ResizableSplit from "@/layouts/default/components/ResizableSplit.vue";
import type { RepoMainView } from "../utils/repoWorkspaceTypes";
import type { Project } from "@/types/project";
import type { SidebarView } from "@/utils/activityBarOrder";

defineOptions({ name: "RepoWorkspaceLayout" });

withDefaults(
  defineProps<{
    project: Project;
    sidebarView: SidebarView;
    mainView: RepoMainView;
    toolbarLoading?: boolean;
    ariaBusy?: boolean;
    ariaLabel?: string;
  }>(),
  { toolbarLoading: false, ariaBusy: undefined, ariaLabel: undefined },
);

const emit = defineEmits<{
  "update:sidebarView": [view: SidebarView];
  "update:mainView": [view: RepoMainView];
}>();
</script>

<template>
  <div
    class="flex h-full min-h-0 flex-col overflow-hidden"
    data-repo-workspace-layout="true"
    :aria-busy="ariaBusy"
    :aria-label="ariaLabel"
  >
    <RepoToolbar
      :key="project.path"
      :project="project"
      :main-view="mainView"
      :loading-shell="toolbarLoading"
      @update:main-view="(view) => emit('update:mainView', view)"
    />
    <slot name="banner" />
    <div class="relative flex min-h-0 flex-1 overflow-hidden">
      <ActivityBar :active="sidebarView" @change="(view) => emit('update:sidebarView', view)" />
      <div class="relative min-h-0 min-w-0 flex-1 overflow-hidden" data-repo-workspace-split="true">
        <ResizableSplit
          orientation="horizontal"
          :default-ratio="22"
          :min-first-px="240"
          :min-second-px="320"
          storage-key="jlgit:split:sidebar-main"
        >
          <template #first>
            <aside class="h-full min-h-0 overflow-hidden">
              <slot name="sidebar" />
            </aside>
          </template>
          <template #second>
            <div class="h-full min-h-0 min-w-0 overflow-hidden">
              <slot name="main" />
            </div>
          </template>
        </ResizableSplit>
        <slot name="overlay" />
      </div>
    </div>
  </div>
</template>

// src/components/layout/RepoWorkspaceLayout.tsx
import type { AriaAttributes, ReactNode } from "react";

import { ActivityBar, type SidebarView } from "@/components/layout/ActivityBar";
import { RepoToolbar, type RepoMainView } from "@/components/layout/RepoToolbar";
import { ResizableSplit } from "@/components/layout/ResizableSplit";

import type { Project } from "@/types/project";

const SIDEBAR_MAIN_SPLIT_KEY = "jlgit:split:sidebar-main";
const SIDEBAR_MIN_WIDTH_PX = 240;

interface RepoWorkspaceLayoutProps extends Pick<AriaAttributes, "aria-busy" | "aria-label"> {
  project: Project;
  sidebarView: SidebarView;
  mainView: RepoMainView;
  toolbarLoading?: boolean;
  sidebar: ReactNode;
  main: ReactNode;
  onSidebarViewChange: (view: SidebarView) => void;
  onMainViewChange: (view: RepoMainView) => void;
}

export function RepoWorkspaceLayout({
  project,
  sidebarView,
  mainView,
  toolbarLoading = false,
  sidebar,
  main,
  onSidebarViewChange,
  onMainViewChange,
  "aria-busy": ariaBusy,
  "aria-label": ariaLabel,
}: RepoWorkspaceLayoutProps) {
  return (
    <div
      className="flex h-full min-h-0 flex-col overflow-hidden"
      data-repo-workspace-layout="true"
      aria-busy={ariaBusy}
      aria-label={ariaLabel}
    >
      <RepoToolbar
        key={project.path}
        project={project}
        mainView={mainView}
        loadingShell={toolbarLoading}
        onMainViewChange={onMainViewChange}
      />

      <div className="relative flex min-h-0 flex-1 overflow-hidden">
        <ActivityBar active={sidebarView} onChange={onSidebarViewChange} />
        <ResizableSplit
          orientation="horizontal"
          defaultRatio={5}
          minFirstPx={SIDEBAR_MIN_WIDTH_PX}
          minSecondPx={320}
          storageKey={SIDEBAR_MAIN_SPLIT_KEY}
          first={<aside className="h-full min-h-0 overflow-hidden">{sidebar}</aside>}
          second={<div className="h-full min-h-0 min-w-0 overflow-hidden">{main}</div>}
        />
      </div>
    </div>
  );
}
