// src/layouts/default/content/WorkspaceHost.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useRoute } from "vue-router";

import { cn } from "@/lib/utils";
import { useZustand } from "@/hooks/core/useZustand";
import { useOpenTabsStore } from "@/store/modules/multipleTab";
import { resolveActiveOpenTab, shouldClearPendingActivation } from "@/utils/repoTabActivation";

import DashboardPage from "@/views/dashboard/index.vue";
import RepoPage from "@/views/repo/index.vue";

defineOptions({ name: "WorkspaceHost" });

const route = useRoute();
const tabs = useZustand(useOpenTabsStore, (state) => state.tabs);
const pendingActiveId = useZustand(useOpenTabsStore, (state) => state.pendingActiveId);
const pendingOriginLocationKey = useZustand(
  useOpenTabsStore,
  (state) => state.pendingOriginLocationKey,
);

const pendingActivationStale = computed(() =>
  shouldClearPendingActivation({
    pendingActiveId: pendingActiveId.value,
    originLocationKey: pendingOriginLocationKey.value,
    currentLocationKey: route.fullPath,
  }),
);

const activeTab = computed(() =>
  resolveActiveOpenTab(
    route.path,
    tabs.value,
    pendingActivationStale.value ? null : pendingActiveId.value,
  ),
);

const activeRepoId = computed(() =>
  activeTab.value?.type === "repository" ? activeTab.value.projectId : null,
);

const showDashboard = computed(
  () =>
    activeTab.value?.type === "new-tab" ||
    (!activeTab.value && (route.path === "/" || route.path.startsWith("/tab/"))),
);

const hasNewTab = computed(() => tabs.value.some((tab) => tab.type === "new-tab"));
const openRepoIdsKey = computed(() =>
  tabs.value
    .filter((tab) => tab.type === "repository")
    .map((tab) => (tab.type === "repository" ? tab.projectId : ""))
    .join("|"),
);

const mountedRepoId = ref<string | null>(activeRepoId.value);

watch(
  [activeRepoId, openRepoIdsKey],
  ([repoId, openIds]) => {
    if (repoId) {
      mountedRepoId.value = repoId;
      return;
    }
    if (!openIds) {
      mountedRepoId.value = null;
    }
  },
  { immediate: true },
);

const repoProjectId = computed(() => activeRepoId.value ?? mountedRepoId.value);
const repoVisible = computed(() => Boolean(activeRepoId.value));
</script>

<template>
  <div class="h-full">
    <div v-if="showDashboard || hasNewTab" :class="cn('h-full', !showDashboard && 'hidden')">
      <DashboardPage :active="showDashboard" />
    </div>
    <div
      v-if="repoProjectId"
      :class="cn('h-full', !repoVisible && 'hidden')"
      :aria-hidden="!repoVisible"
    >
      <RepoPage :project-id="repoProjectId" :active="repoVisible" />
    </div>
  </div>
</template>

// src/components/layout/WorkspaceHost.tsx
import { Activity, useEffect, useMemo, useState } from "react";
import { useLocation } from "react-router-dom";

import { cn } from "@/lib/utils";

import { DashboardPage } from "@/pages/DashboardPage";
import { RepoPage } from "@/pages/RepoPage";

import { useOpenTabsStore } from "@/store/useOpenTabsStore";
import { resolveActiveOpenTab, shouldClearPendingActivation } from "@/utils/repoTabActivation";

/**
 * 工作区宿主（性能约束）：
 * - 全局仅一份 useRepoStore → 同时只挂一个 RepoPage
 * - 新标签页 Activity 保活；仓库页离开时 hidden 保活
 */
export function WorkspaceHost() {
  const location = useLocation();
  const tabs = useOpenTabsStore((state) => state.tabs);
  const pendingActiveId = useOpenTabsStore((state) => state.pendingActiveId);
  const pendingOriginLocationKey = useOpenTabsStore((state) => state.pendingOriginLocationKey);

  const pendingActivationStale = shouldClearPendingActivation({
    pendingActiveId,
    originLocationKey: pendingOriginLocationKey,
    currentLocationKey: location.key,
  });
  const activeTab = resolveActiveOpenTab(
    location.pathname,
    tabs,
    pendingActivationStale ? null : pendingActiveId,
  );
  const activeRepoId = activeTab?.type === "repository" ? activeTab.projectId : null;
  const showDashboard =
    activeTab?.type === "new-tab" ||
    (!activeTab && (location.pathname === "/" || location.pathname.startsWith("/tab/")));
  const hasNewTab = tabs.some((tab) => tab.type === "new-tab");

  const openRepoIdsKey = useMemo(
    () =>
      tabs
        .filter((tab) => tab.type === "repository")
        .map((tab) => (tab.type === "repository" ? tab.projectId : ""))
        .join("|"),
    [tabs],
  );

  const [mountedRepoId, setMountedRepoId] = useState<string | null>(activeRepoId);

  useEffect(() => {
    if (activeRepoId) {
      setMountedRepoId(activeRepoId);
      return;
    }
    if (!openRepoIdsKey) {
      setMountedRepoId(null);
    }
  }, [activeRepoId, openRepoIdsKey]);

  const repoProjectId = activeRepoId ?? mountedRepoId;
  const repoVisible = Boolean(activeRepoId);

  return (
    <>
      {(showDashboard || hasNewTab) && (
        <Activity mode={showDashboard ? "visible" : "hidden"}>
          <div className="h-full">
            <DashboardPage active={showDashboard} />
          </div>
        </Activity>
      )}

      {repoProjectId ? (
        <div className={cn("h-full", !repoVisible && "hidden")} aria-hidden={!repoVisible}>
          <RepoPage projectId={repoProjectId} active={repoVisible} />
        </div>
      ) : null}
    </>
  );
}
