// src/components/layout/RepoToolbar.tsx
import { useMemo, useState, type CSSProperties } from "react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import {
  ArrowDownToLine,
  ArrowUpFromLine,
  Check,
  ChevronDown,
  Clock3,
  CloudUpload,
  FileCode2,
  Folder,
  GitBranch as GitBranchIcon,
  GitCompareArrows,
  LayoutDashboard,
  ListTree,
  RotateCcw,
  RotateCw,
  Search,
  Terminal,
} from "lucide-react";
import { toast } from "sonner";

import { DropdownMenuScrollArea } from "@/components/common/DropdownMenuScrollArea";
import { LocalBranchMenuList } from "@/components/git/LocalBranchMenuList";
import { ProjectIcon } from "@/components/project/ProjectIcon";
import { Button } from "@/components/ui/button";
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuTrigger,
} from "@/components/ui/context-menu";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Spinner } from "@/components/ui/spinner";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { useConflictOperationGuard } from "@/hooks/useConflictOperationGuard";
import { useWindowChromeLayout } from "@/hooks/useWindowChromeLayout";
import { cn } from "@/lib/utils";

import { systemOpenService } from "@/services/system/system.open";
import { openBranchCompareWindow } from "@/services/window/branchCompareWindow";
import { useOpenTabsStore } from "@/store/useOpenTabsStore";
import { useProjectStore } from "@/store/useProjectStore";
import { useRepoStore } from "@/store/useRepoStore";

import { toUserMessage } from "@/types/error";
import type { GitBranch } from "@/types/git";
import type { Project } from "@/types/project";
import { isLocalBranchPublished } from "@/utils/branchPublish";
import { isPushRejectedError, toastPushError } from "@/utils/gitPushError";
import { revealInFileManagerLabel as revealInFileManagerLabelForOs } from "@/utils/platformLabels";

/**
 * 工具栏默认比较：源=当前分支；目标优先 upstream，其次 origin/<name>，否则自身。
 */
function resolveDefaultCompareTarget(
  branches: readonly GitBranch[],
  currentBranch: string,
): string {
  const local = branches.find((branch) => !branch.isRemote && branch.name === currentBranch);
  const upstream = local?.upstream?.trim() ?? "";
  if (upstream) {
    return upstream;
  }
  const originTwin = `origin/${currentBranch}`;
  if (branches.some((branch) => branch.isRemote && branch.name === originTwin)) {
    return originTwin;
  }
  return currentBranch;
}

const noDragStyle = { WebkitAppRegion: "no-drag" } as CSSProperties;

export type RepoMainView = "workspace" | "changes" | "history";

interface RepoToolbarProps {
  project: Project;
  mainView: RepoMainView;
  onMainViewChange: (view: RepoMainView) => void;
}

/** 顶栏标签下方的仓库工具条：仓库 / 视图 / 分支 / 同步 */
export function RepoToolbar({ project, mainView, onMainViewChange }: RepoToolbarProps) {
  const { t } = useTranslation();
  const { os, isMacOverlay } = useWindowChromeLayout();
  const dragProps = isMacOverlay ? ({ "data-tauri-drag-region": true } as const) : {};
  const revealInFileManagerLabel = revealInFileManagerLabelForOs(os, t);
  const navigate = useNavigate();

  const projects = useProjectStore((state) => state.projects);
  const openRepositoryTab = useOpenTabsStore((state) => state.openRepositoryTab);

  const status = useRepoStore((state) => state.status);
  const branches = useRepoStore((state) => state.branches);
  const loading = useRepoStore((state) => state.loading);
  const checkout = useRepoStore((state) => state.checkout);
  const fetchRemote = useRepoStore((state) => state.fetch);
  const pullRemote = useRepoStore((state) => state.pull);
  const pushRemote = useRepoStore((state) => state.push);
  const undoCommit = useRepoStore((state) => state.undoCommit);

  const [checkingOut, setCheckingOut] = useState(false);
  const [branchMenuOpen, setBranchMenuOpen] = useState(false);
  const [fetching, setFetching] = useState(false);
  const [pulling, setPulling] = useState(false);
  const [pushing, setPushing] = useState(false);
  const [projectFilter, setProjectFilter] = useState("");
  const { guard: guardWriteOp, dialog: conflictGuardDialog } = useConflictOperationGuard();

  const changeCount = useMemo(() => {
    return status?.entries.length ?? 0;
  }, [status?.entries.length]);

  const ahead = status?.ahead ?? 0;
  const behind = status?.behind ?? 0;
  const localBranches = useMemo(() => branches.filter((branch) => !branch.isRemote), [branches]);
  /** 下拉：本地在上；仅纳入 origin/ 开头的远端；组内按名称排序 */
  const menuBranches = useMemo(() => {
    const byName = (left: GitBranch, right: GitBranch) => left.name.localeCompare(right.name);
    const local = branches.filter((branch) => !branch.isRemote).sort(byName);
    const originRemote = branches
      .filter((branch) => branch.isRemote && branch.name.startsWith("origin/"))
      .sort(byName);
    return [...local, ...originRemote];
  }, [branches]);
  // 当前检出分支尚未发布到远端时，在「推送」右侧显示「发布分支」
  const needsPublish = useMemo(() => {
    if (!status?.branch || status.detached) {
      return false;
    }
    const current = localBranches.find((branch) => branch.name === status.branch);
    if (!current) {
      return !status.upstream;
    }
    return !isLocalBranchPublished(current, branches);
  }, [branches, localBranches, status?.branch, status?.detached, status?.upstream]);
  const syncBusy = fetching || pulling || pushing || loading;

  const branchLabel = status?.detached
    ? t("repo.detached")
    : (status?.branch ?? t("repo.currentBranch"));

  const sortedProjects = useMemo(() => {
    return [...projects].sort((a, b) => {
      const aTime = a.lastOpenedAt ?? a.updatedAt;
      const bTime = b.lastOpenedAt ?? b.updatedAt;
      return bTime.localeCompare(aTime);
    });
  }, [projects]);

  const filteredProjects = useMemo(() => {
    const query = projectFilter.trim().toLowerCase();
    if (!query) {
      return sortedProjects;
    }
    return sortedProjects.filter(
      (item) => item.name.toLowerCase().includes(query) || item.path.toLowerCase().includes(query),
    );
  }, [sortedProjects, projectFilter]);

  function handleSelectProject(next: Project): void {
    if (next.id === project.id) {
      return;
    }
    // 先导航立刻切换标签高亮；数据加载由 RepoPage 完成
    openRepositoryTab(next.id);
    navigate(`/repo/${next.id}`);
  }

  async function handleCheckout(branchName: string): Promise<void> {
    if (branchName === status?.branch) {
      return;
    }
    if (!guardWriteOp()) {
      return;
    }

    setCheckingOut(true);
    try {
      await checkout(branchName);
    } catch (error) {
      toast.error(toUserMessage(error));
    } finally {
      setCheckingOut(false);
    }
  }

  async function handleCheckUpdate(): Promise<void> {
    if (syncBusy) {
      return;
    }

    setFetching(true);
    try {
      await fetchRemote();
    } catch (error) {
      toast.error(toUserMessage(error));
    } finally {
      setFetching(false);
    }
  }

  async function handlePull(): Promise<void> {
    if (syncBusy || needsPublish) {
      return;
    }
    if (!guardWriteOp()) {
      return;
    }

    setPulling(true);
    try {
      // 有当前分支时显式 pull origin <branch>，与 ugit 一致；分离头则走 upstream
      const branch = status?.detached ? undefined : (status?.branch ?? undefined);
      const result = await pullRemote({
        remote: "origin",
        branch,
      });
      if (result.conflict) {
        toast.error(t("repo.pullConflict"));
      }
    } catch (error) {
      toast.error(toUserMessage(error));
    } finally {
      setPulling(false);
    }
  }

  async function handlePush(): Promise<void> {
    if (syncBusy || ahead <= 0) {
      return;
    }

    setPushing(true);
    const toastId = toast.loading(t("repo.pushStart"));
    try {
      const result = await pushRemote();
      const seconds = (result.elapsedMs / 1000).toFixed(1);
      toast.success(t("repo.pushSuccess", { remote: result.remote, seconds }), { id: toastId });
    } catch (error) {
      toastPushError(error, {
        toastId,
        onUpdate: () => void handlePull(),
      });
      // 静默 fetch，刷新 behind 角标，便于用户直接点「更新」
      if (isPushRejectedError(error)) {
        void fetchRemote().catch(() => undefined);
      }
    } finally {
      setPushing(false);
    }
  }

  async function handlePublish(): Promise<void> {
    if (syncBusy || !needsPublish || !status?.branch) {
      return;
    }

    setPushing(true);
    const toastId = toast.loading(t("repo.publishStart"));
    try {
      const result = await pushRemote({
        remote: "origin",
        branch: status.branch,
        setUpstream: true,
      });
      const seconds = (result.elapsedMs / 1000).toFixed(1);
      toast.success(t("repo.publishSuccess", { remote: result.remote, seconds }), { id: toastId });
    } catch (error) {
      toastPushError(error, {
        toastId,
        onUpdate: () => void handlePull(),
      });
      if (isPushRejectedError(error)) {
        void fetchRemote().catch(() => undefined);
      }
    } finally {
      setPushing(false);
    }
  }

  function handleUndoCommit(): void {
    if (syncBusy || ahead <= 0) {
      toast.message(t("repo.errors.nothingToUndo"));
      return;
    }
    if (!guardWriteOp()) {
      return;
    }
    void (async () => {
      try {
        await undoCommit();
      } catch (error) {
        toast.error(toUserMessage(error));
      }
    })();
  }

  async function handleOpenInEditor(): Promise<void> {
    try {
      await systemOpenService.openInEditor(project.path);
    } catch (error) {
      toast.error(toUserMessage(error));
    }
  }

  async function handleRevealInFinder(): Promise<void> {
    try {
      await systemOpenService.revealInFileManager(project.path);
    } catch (error) {
      toast.error(toUserMessage(error));
    }
  }

  async function handleOpenInTerminal(): Promise<void> {
    try {
      await systemOpenService.openTerminal(project.path);
    } catch (error) {
      toast.error(toUserMessage(error));
    }
  }

  function handleOpenBranchCompare(): void {
    const currentBranch = status?.branch ?? branches.find((branch) => branch.isCurrent)?.name;
    if (!currentBranch) {
      toast.error(t("repo.openBranchCompareNoBranch"));
      return;
    }
    void openBranchCompareWindow({
      projectId: project.id,
      mode: "branch",
      base: currentBranch,
      target: resolveDefaultCompareTarget(branches, currentBranch),
    }).catch((error: unknown) => {
      toast.error(toUserMessage(error) || t("agent.compareBranchesFailed"));
    });
  }

  const viewItems: Array<{
    id: RepoMainView;
    label: string;
    icon: typeof LayoutDashboard;
    badge?: number;
  }> = [
    { id: "workspace", label: t("repo.viewWorkspace"), icon: LayoutDashboard },
    {
      id: "changes",
      label: t("repo.viewChanges"),
      icon: ListTree,
      badge: changeCount > 0 ? changeCount : undefined,
    },
    { id: "history", label: t("repo.viewHistory"), icon: Clock3 },
  ];

  return (
    <div
      {...dragProps}
      className="border-border bg-background flex h-11 shrink-0 items-center gap-2 border-b px-2"
    >
      {/* 仓库切换 */}
      <DropdownMenu
        onOpenChange={(open) => {
          if (!open) {
            setProjectFilter("");
          }
        }}
      >
        <DropdownMenuTrigger asChild>
          <Button
            type="button"
            variant="ghost"
            className="h-8 w-44 shrink-0 justify-start gap-1.5 px-2"
            style={noDragStyle}
            aria-label={t("repo.switchProject")}
          >
            <ProjectIcon name={project.icon} className="size-3.5 shrink-0" />
            <span className="min-w-0 flex-1 truncate text-left text-sm font-medium">
              {project.name}
            </span>
            <ChevronDown className="text-muted-foreground size-3.5 shrink-0" aria-hidden="true" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="start" className="w-72 overflow-hidden p-0">
          {/* 间距对齐历史「用户」筛选 / 分支下拉 */}
          <div className="border-border border-b p-1.5">
            <div className="relative">
              <Search
                className="text-muted-foreground pointer-events-none absolute top-1/2 left-2 size-3.5 -translate-y-1/2"
                aria-hidden="true"
              />
              <Input
                value={projectFilter}
                onChange={(event) => setProjectFilter(event.target.value)}
                placeholder={t("repo.switchProjectFilter")}
                className="h-7 pl-7 text-xs shadow-none"
                aria-label={t("repo.switchProjectFilter")}
                autoFocus
                onKeyDown={(event) => event.stopPropagation()}
                onClick={(event) => event.stopPropagation()}
                onPointerDown={(event) => event.stopPropagation()}
              />
            </div>
          </div>
          <DropdownMenuScrollArea
            itemCount={filteredProjects.length}
            itemHeight={52}
            maxHeight={288}
            availableHeightOffset={41}
          >
            <div className="min-w-0 p-1">
              {filteredProjects.length === 0 ? (
                <p className="text-muted-foreground px-2 py-3 text-center text-xs">
                  {t("repo.switchProjectNoMatch")}
                </p>
              ) : (
                filteredProjects.map((item) => (
                  <DropdownMenuItem
                    key={item.id}
                    className="flex w-full max-w-full min-w-0 flex-col items-start gap-0.5 overflow-hidden py-2"
                    onSelect={() => {
                      handleSelectProject(item);
                    }}
                  >
                    <div className="flex w-full max-w-full min-w-0 items-center gap-2">
                      <span className="min-w-0 flex-1 truncate font-medium">{item.name}</span>
                      {item.id === project.id ? (
                        <Check className="size-3.5 shrink-0" aria-hidden="true" />
                      ) : null}
                    </div>
                    <span
                      className="text-muted-foreground block w-full max-w-full min-w-0 truncate text-xs"
                      title={item.path}
                    >
                      {item.path}
                    </span>
                  </DropdownMenuItem>
                ))
              )}
            </div>
          </DropdownMenuScrollArea>
        </DropdownMenuContent>
      </DropdownMenu>

      <div className="bg-border h-6 w-px shrink-0" aria-hidden="true" />

      {/* 主视图切换 */}
      <div
        className="flex items-center gap-0.5"
        role="tablist"
        aria-label={t("repo.mainViews")}
        style={noDragStyle}
      >
        {viewItems.map((item) => {
          const Icon = item.icon;
          const isActive = mainView === item.id;

          return (
            <Button
              key={item.id}
              type="button"
              role="tab"
              aria-selected={isActive}
              variant="ghost"
              size="sm"
              className={cn(
                "h-8 gap-1.5 transition-colors",
                isActive
                  ? "bg-primary/10 text-primary hover:bg-primary/15 hover:text-primary"
                  : "text-muted-foreground",
              )}
              onClick={() => onMainViewChange(item.id)}
            >
              <Icon className="size-3.5" aria-hidden="true" />
              <span>{item.label}</span>
              {item.badge != null ? (
                <span className="bg-primary text-primary-foreground ml-0.5 inline-flex min-w-4 items-center justify-center rounded-full px-1 text-[10px] leading-4 font-semibold">
                  {item.badge > 99 ? "99+" : item.badge}
                </span>
              ) : null}
            </Button>
          );
        })}
      </div>

      <div className="bg-border h-6 w-px shrink-0" aria-hidden="true" />

      {/* 分支：固定宽度 + truncate，避免短/长分支名切换时工具栏抖动 */}
      <DropdownMenu open={branchMenuOpen} onOpenChange={setBranchMenuOpen}>
        <DropdownMenuTrigger asChild>
          <Button
            type="button"
            variant="ghost"
            className="border-border h-8 w-40 shrink-0 justify-start gap-1.5 border px-2.5 shadow-none"
            style={noDragStyle}
            disabled={checkingOut || loading}
            aria-label={t("repo.branchLabel")}
            title={branchLabel}
          >
            {checkingOut ? (
              <Spinner className="size-3.5 shrink-0" />
            ) : (
              <GitBranchIcon className="size-3.5 shrink-0" aria-hidden="true" />
            )}
            <span className="min-w-0 flex-1 truncate text-left text-sm font-medium">
              {branchLabel}
            </span>
            <ChevronDown className="text-muted-foreground size-3.5 shrink-0" aria-hidden="true" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent
          align="start"
          // 禁止 Content 原生滚动，滚动交给内部 ScrollArea；p-0 对齐历史用户筛选
          className="w-72 overflow-hidden p-0"
        >
          <LocalBranchMenuList
            branches={menuBranches}
            checkingOut={checkingOut}
            open={branchMenuOpen}
            onCheckout={(branchName) => {
              void handleCheckout(branchName);
            }}
          />
        </DropdownMenuContent>
      </DropdownMenu>

      {/* 同步：检查更新 / 更新(pull) / 推送（右键：撤销提交） */}
      <div className="flex shrink-0 items-center gap-1" style={noDragStyle}>
        <Tooltip delayDuration={300}>
          <TooltipTrigger asChild>
            <Button
              type="button"
              variant="ghost"
              size="sm"
              className="h-8"
              disabled={syncBusy}
              onClick={() => void handleCheckUpdate()}
            >
              {fetching ? (
                <Spinner className="size-3.5" />
              ) : (
                <RotateCw className="size-3.5" aria-hidden="true" />
              )}
              <span>{t("repo.checkUpdate")}</span>
            </Button>
          </TooltipTrigger>
          <TooltipContent>{t("repo.checkUpdate")}</TooltipContent>
        </Tooltip>

        <Tooltip delayDuration={300}>
          <TooltipTrigger asChild>
            <span className="inline-flex">
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="relative h-8 gap-1.5"
                disabled={syncBusy || needsPublish}
                onClick={() => void handlePull()}
              >
                {pulling ? (
                  <Spinner className="size-3.5" />
                ) : (
                  <ArrowDownToLine className="size-3.5" aria-hidden="true" />
                )}
                <span>{t("repo.pull")}</span>
                {behind > 0 ? (
                  <span
                    className="bg-primary text-primary-foreground ml-0.5 inline-flex size-4 items-center justify-center rounded-full text-[10px] leading-none font-semibold"
                    aria-label={t("repo.unpulledCount", { count: behind })}
                  >
                    {behind > 99 ? "99+" : behind}
                  </span>
                ) : null}
              </Button>
            </span>
          </TooltipTrigger>
          <TooltipContent>
            {needsPublish
              ? t("repo.pullNeedsPublish")
              : behind > 0
                ? t("repo.unpulledCount", { count: behind })
                : t("repo.pullHint")}
          </TooltipContent>
        </Tooltip>

        {needsPublish ? null : (
          <ContextMenu>
            <Tooltip delayDuration={300}>
              <TooltipTrigger asChild>
                {/* disabled 时包一层，保证仍能显示「无可推送」提示 */}
                <span className="inline-flex">
                  <ContextMenuTrigger asChild>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="relative h-8 gap-1.5"
                      disabled={syncBusy || ahead <= 0}
                      onClick={() => void handlePush()}
                    >
                      {pushing ? (
                        <Spinner className="size-3.5" />
                      ) : (
                        <ArrowUpFromLine className="size-3.5" aria-hidden="true" />
                      )}
                      <span>{t("repo.push")}</span>
                      {ahead > 0 ? (
                        <span
                          className="bg-primary text-primary-foreground ml-0.5 inline-flex size-4 items-center justify-center rounded-full text-[10px] leading-none font-semibold"
                          aria-label={t("repo.unpushedCount", { count: ahead })}
                        >
                          {ahead > 99 ? "99+" : ahead}
                        </span>
                      ) : null}
                    </Button>
                  </ContextMenuTrigger>
                </span>
              </TooltipTrigger>
              <TooltipContent>
                {ahead <= 0 ? t("repo.pushNothing") : t("repo.unpushedCount", { count: ahead })}
              </TooltipContent>
            </Tooltip>
            <ContextMenuContent className="min-w-40">
              <ContextMenuItem disabled={ahead <= 0} onSelect={handleUndoCommit}>
                <RotateCcw className="size-3.5" aria-hidden="true" />
                {t("repo.undoCommitMenu")}
              </ContextMenuItem>
            </ContextMenuContent>
          </ContextMenu>
        )}

        {needsPublish ? (
          <Tooltip delayDuration={300}>
            <TooltipTrigger asChild>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="relative h-8 gap-1.5"
                disabled={syncBusy}
                onClick={() => void handlePublish()}
              >
                {pushing ? (
                  <Spinner className="size-3.5" />
                ) : (
                  <CloudUpload className="size-3.5" aria-hidden="true" />
                )}
                <span>{t("repo.publishBranch")}</span>
              </Button>
            </TooltipTrigger>
            <TooltipContent>{t("repo.publishBranchHint")}</TooltipContent>
          </Tooltip>
        ) : null}
      </div>

      {/* 右侧：分支比较 + 外部打开 */}
      <div className="ml-auto flex shrink-0 items-center gap-0.5" style={noDragStyle}>
        <Tooltip delayDuration={300}>
          <TooltipTrigger asChild>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className="size-8"
              aria-label={t("repo.openInEditor")}
              onClick={() => void handleOpenInEditor()}
            >
              <FileCode2 className="size-3.5" aria-hidden="true" />
            </Button>
          </TooltipTrigger>
          <TooltipContent>{t("repo.openInEditor")}</TooltipContent>
        </Tooltip>

        <Tooltip delayDuration={300}>
          <TooltipTrigger asChild>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className="size-8"
              aria-label={t("repo.openBranchCompare")}
              onClick={handleOpenBranchCompare}
            >
              <GitCompareArrows className="size-3.5" aria-hidden="true" />
            </Button>
          </TooltipTrigger>
          <TooltipContent>{t("repo.openBranchCompare")}</TooltipContent>
        </Tooltip>

        <Tooltip delayDuration={300}>
          <TooltipTrigger asChild>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className="size-8"
              aria-label={revealInFileManagerLabel}
              onClick={() => void handleRevealInFinder()}
            >
              <Folder className="size-3.5" aria-hidden="true" />
            </Button>
          </TooltipTrigger>
          <TooltipContent>{revealInFileManagerLabel}</TooltipContent>
        </Tooltip>

        <Tooltip delayDuration={300}>
          <TooltipTrigger asChild>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className="size-8"
              aria-label={t("repo.openInTerminal")}
              onClick={() => void handleOpenInTerminal()}
            >
              <Terminal className="size-3.5" aria-hidden="true" />
            </Button>
          </TooltipTrigger>
          <TooltipContent>{t("repo.openInTerminal")}</TooltipContent>
        </Tooltip>
      </div>

      {conflictGuardDialog}
    </div>
  );
}

// src/views/repo/components/RepoToolbar.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useRouter } from "vue-router";

import { Button, Dropdown, Tooltip, message, type MenuProps } from "antdv-next";
import { useI18n } from "vue-i18n";

import { Icon } from "@/components/Icon";
import { ProjectIcon } from "@/components/Project";
import type { RepoMainView } from "../utils/repoWorkspaceTypes";
import { useWindowChromeLayout } from "@/hooks/core/useWindowChromeLayout";
import { useZustand } from "@/hooks/core/useZustand";
import { cn } from "@/lib/utils";
import { openBranchCompareWindow } from "@/services/window/branchCompareWindow";
import { useAppPrefsStoreWithOut } from "@/store/modules/app";
import { useOpenTabsStoreWithOut } from "@/store/modules/multipleTab";
import { useRepoStore, useRepoStoreWithOut } from "@/store/modules/repo";
import { toUserMessage } from "@/types/error";
import type { GitBranch } from "@/types/git";
import type { Project } from "@/types/project";
import { resolveDefaultCompareTarget } from "@/utils/branchCompareTarget";
import { isLocalBranchPublished } from "@/utils/branchPublish";
import { isPushRejectedError, toastPushError } from "@/utils/gitPushError";

defineOptions({ name: "RepoToolbar" });

const props = withDefaults(
  defineProps<{
    project: Project;
    mainView: RepoMainView;
    loadingShell?: boolean;
  }>(),
  { loadingShell: false },
);

const emit = defineEmits<{
  "update:mainView": [view: RepoMainView];
}>();

const EMPTY_BRANCHES: GitBranch[] = [];

const { t } = useI18n();
const router = useRouter();
const { isMacOverlay } = useWindowChromeLayout();
const storeStatus = useZustand(useRepoStore, (state) => state.status);
const storeBranches = useZustand(useRepoStore, (state) => state.branches);
const storeLoading = useZustand(useRepoStore, (state) => state.loading);
const status = computed(() => (props.loadingShell ? null : storeStatus.value));
const branches = computed(() => (props.loadingShell ? EMPTY_BRANCHES : storeBranches.value));
const loading = computed(() => props.loadingShell || storeLoading.value);
const checkingOut = ref(false);
const fetching = ref(false);
const pulling = ref(false);
const pushing = ref(false);

watch(
  () => props.project.path,
  () => {
    checkingOut.value = false;
    fetching.value = false;
    pulling.value = false;
    pushing.value = false;
  },
);

const changeCount = computed(() => status.value?.entries.length ?? 0);
const ahead = computed(() => status.value?.ahead ?? 0);
const behind = computed(() => status.value?.behind ?? 0);
const localBranches = computed(() => branches.value.filter((branch) => !branch.isRemote));
const needsPublish = computed(() => {
  if (!status.value?.branch || status.value.detached) {
    return false;
  }
  const current = localBranches.value.find((branch) => branch.name === status.value?.branch);
  if (!current) {
    return !status.value.upstream;
  }
  return !isLocalBranchPublished(current, branches.value);
});
const syncBusy = computed(() => fetching.value || pulling.value || pushing.value || loading.value);
const branchSwitchLocked = computed(() => checkingOut.value || pushing.value || pulling.value);
const branchLabel = computed(() =>
  status.value?.detached ? t("repo.detached") : (status.value?.branch ?? t("repo.currentBranch")),
);

const views = computed(() => [
  { id: "workspace" as const, icon: "LayoutDashboard", label: t("repo.viewWorkspace") },
  { id: "changes" as const, icon: "ListTree", label: t("repo.viewChanges") },
  { id: "history" as const, icon: "Clock3", label: t("repo.viewHistory") },
]);

const branchMenuItems = computed<MenuProps["items"]>(() =>
  localBranches.value.map((branch) => ({
    key: branch.name,
    label: branch.name,
    disabled: branchSwitchLocked.value,
  })),
);

async function handleCheckout(branchName: string): Promise<void> {
  if (branchName === status.value?.branch) {
    return;
  }
  checkingOut.value = true;
  try {
    await useRepoStoreWithOut().checkout(branchName);
  } catch (error) {
    message.error(toUserMessage(error));
  } finally {
    checkingOut.value = false;
  }
}

async function handleFetch(): Promise<void> {
  if (syncBusy.value) {
    return;
  }
  fetching.value = true;
  try {
    await useRepoStoreWithOut().fetch();
  } catch (error) {
    message.error(toUserMessage(error));
  } finally {
    fetching.value = false;
  }
}

async function handlePull(): Promise<void> {
  if (syncBusy.value) {
    return;
  }
  pulling.value = true;
  try {
    const rebase = useAppPrefsStoreWithOut().pullStrategy === "rebase";
    const result = await useRepoStoreWithOut().pull({ rebase });
    if (result.conflict) {
      message.error(t("repo.pullConflict"));
    }
  } catch (error) {
    message.error(toUserMessage(error));
  } finally {
    pulling.value = false;
  }
}

async function handlePush(): Promise<void> {
  if (syncBusy.value) {
    return;
  }
  pushing.value = true;
  try {
    const current = status.value?.branch;
    await useRepoStoreWithOut().push({
      remote: "origin",
      ...(needsPublish.value && current
        ? { branch: current, setUpstream: true }
        : current
          ? { branch: current }
          : {}),
    });
  } catch (error) {
    toastPushError(error, {
      onUpdate: () => {
        void handlePull();
      },
    });
    if (isPushRejectedError(error)) {
      void useRepoStoreWithOut()
        .fetch()
        .catch(() => undefined);
    }
  } finally {
    pushing.value = false;
  }
}

async function handleRefresh(): Promise<void> {
  try {
    await useRepoStoreWithOut().refreshStatus();
  } catch (error) {
    message.error(toUserMessage(error));
  }
}

function goDashboard(): void {
  const tabId = useOpenTabsStoreWithOut().openNewTab();
  void router.push(`/tab/${tabId}`);
}

function handleOpenBranchCompare(): void {
  const currentBranch =
    status.value?.branch ?? branches.value.find((branch) => branch.isCurrent)?.name;
  if (!currentBranch) {
    message.error(t("repo.openBranchCompareNoBranch"));
    return;
  }
  void openBranchCompareWindow({
    projectId: props.project.id,
    mode: "branch",
    base: currentBranch,
    target: resolveDefaultCompareTarget(branches.value, currentBranch),
  }).catch((error: unknown) => {
    message.error(toUserMessage(error) || t("agent.compareBranchesFailed"));
  });
}
</script>

<template>
  <div
    class="border-border flex h-10 shrink-0 items-center gap-2 border-b px-3"
    :data-tauri-drag-region="isMacOverlay ? true : undefined"
  >
    <button
      type="button"
      class="hover:bg-accent/60 flex min-w-0 items-center gap-2 rounded-md px-1.5 py-1"
      :aria-label="t('dashboard.title')"
      @click="goDashboard"
    >
      <ProjectIcon :name="project.icon" class-name="size-4 shrink-0" />
      <span class="truncate text-sm font-medium">{{ project.name }}</span>
    </button>

    <div class="bg-border mx-1 h-4 w-px shrink-0" />

    <div class="flex items-center gap-0.5">
      <Tooltip v-for="view in views" :key="view.id" :title="view.label">
        <button
          type="button"
          :class="
            cn(
              'inline-flex h-7 items-center gap-1 rounded-md px-2 text-xs transition-colors',
              mainView === view.id
                ? 'bg-primary/10 text-primary'
                : 'text-muted-foreground hover:bg-accent/60',
            )
          "
          :aria-pressed="mainView === view.id"
          @click="emit('update:mainView', view.id)"
        >
          <Icon :name="view.icon" :size="14" />
          <span>{{ view.label }}</span>
          <span v-if="view.id === 'changes' && changeCount > 0" class="tabular-nums">
            {{ changeCount }}
          </span>
        </button>
      </Tooltip>
    </div>

    <div class="min-w-2 flex-1" :data-tauri-drag-region="isMacOverlay ? true : undefined" />

    <Dropdown
      :trigger="['click']"
      :disabled="branchSwitchLocked || loadingShell"
      :menu="{
        items: branchMenuItems,
        onClick: ({ key }) => void handleCheckout(String(key)),
      }"
    >
      <Button size="small" :disabled="branchSwitchLocked || loadingShell" :loading="checkingOut">
        <Icon name="GitBranch" :size="14" />
        <span class="max-w-40 truncate">{{ branchLabel }}</span>
        <Icon name="ChevronDown" :size="12" />
      </Button>
    </Dropdown>

    <Tooltip :title="t('repo.openBranchCompare')">
      <Button
        size="small"
        :aria-label="t('repo.openBranchCompare')"
        :disabled="loadingShell"
        @click="handleOpenBranchCompare"
      >
        <Icon name="GitCompareArrows" :size="14" />
      </Button>
    </Tooltip>

    <div class="text-muted-foreground flex items-center gap-1 text-xs tabular-nums">
      <span v-if="ahead > 0">↑{{ ahead }}</span>
      <span v-if="behind > 0">↓{{ behind }}</span>
    </div>

    <Tooltip :title="t('repo.checkUpdate')">
      <Button
        size="small"
        :aria-label="t('repo.checkUpdate')"
        :disabled="syncBusy || loadingShell"
        :loading="fetching"
        @click="void handleFetch()"
      >
        <Icon name="CloudUpload" :size="14" />
      </Button>
    </Tooltip>
    <Tooltip :title="t('repo.pull')">
      <Button
        size="small"
        :aria-label="t('repo.pull')"
        :disabled="syncBusy || loadingShell"
        :loading="pulling"
        @click="void handlePull()"
      >
        <Icon name="ArrowDownToLine" :size="14" />
      </Button>
    </Tooltip>
    <Tooltip :title="needsPublish ? t('repo.publishBranch') : t('repo.push')">
      <Button
        size="small"
        :aria-label="needsPublish ? t('repo.publishBranch') : t('repo.push')"
        :disabled="syncBusy || loadingShell"
        :loading="pushing"
        @click="void handlePush()"
      >
        <Icon name="ArrowUpFromLine" :size="14" />
      </Button>
    </Tooltip>
    <Tooltip :title="t('repo.refresh')">
      <Button
        size="small"
        :aria-label="t('repo.refresh')"
        :disabled="loadingShell"
        @click="void handleRefresh()"
      >
        <Icon name="RotateCw" :size="14" />
      </Button>
    </Tooltip>
  </div>
</template>
