// src/components/Git/src/BranchManageWorkspace.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";

import { Button, Checkbox, Empty, Input, Modal, Tag, Tooltip, message } from "antdv-next";
import dayjs from "dayjs";
import { useI18n } from "vue-i18n";

import { AppLoadingScreen, HighlightText } from "@/components/Common";
import { Icon } from "@/components/Icon";
import AppWindowHeader from "@/layouts/page/AppWindowHeader.vue";
import { ScrollArea } from "@/components/ScrollArea";
import { cn } from "@/lib/utils";
import { deleteBranch, listBranches } from "@/services/git";
import { toUserMessage } from "@/types/error";
import type { GitBranch } from "@/types/git";
import type { Project } from "@/types/project";
import { isBranchActive } from "@/utils/branchActivity";
import { formatCommitDateTime } from "@/utils/formatCommitDateTime";

defineOptions({ name: "BranchManageWorkspace" });

const props = defineProps<{
  project: Project;
}>();

type ScopeFilter = "local" | "remote";
type ActivityFilter = "all" | "active" | "inactive";
type SortDirection = "asc" | "desc";

const { t } = useI18n();
const branches = ref<GitBranch[]>([]);
const loading = ref(true);
const refreshing = ref(false);
const error = ref<string | null>(null);
const scope = ref<ScopeFilter>("local");
const activity = ref<ActivityFilter>("all");
const search = ref("");
const sortDir = ref<SortDirection>("desc");
const deleteTarget = ref<GitBranch | null>(null);
const deleteRemoteAlso = ref(false);
const deleteBusy = ref(false);

const scopedBranches = computed(() =>
  branches.value.filter((branch) => (scope.value === "local" ? !branch.isRemote : branch.isRemote)),
);

const activityCounts = computed(() => {
  let activeCount = 0;
  let inactiveCount = 0;
  for (const branch of scopedBranches.value) {
    if (isBranchActive(branch.tipAuthoredAt)) {
      activeCount += 1;
    } else {
      inactiveCount += 1;
    }
  }
  return { all: scopedBranches.value.length, active: activeCount, inactive: inactiveCount };
});

const visibleBranches = computed(() => {
  const query = search.value.trim().toLowerCase();
  let next = scopedBranches.value;
  if (activity.value === "active") {
    next = next.filter((branch) => isBranchActive(branch.tipAuthoredAt));
  } else if (activity.value === "inactive") {
    next = next.filter((branch) => !isBranchActive(branch.tipAuthoredAt));
  }
  if (query) {
    next = next.filter((branch) => {
      const haystack =
        `${branch.name} ${branch.upstream ?? ""} ${branch.tipShortId} ${branch.tipAuthorName}`.toLowerCase();
      return haystack.includes(query);
    });
  }
  return [...next].sort((left, right) => compareByTime(left, right, sortDir.value));
});

const deleteHasRemote = computed(() => {
  if (!deleteTarget.value || deleteTarget.value.isRemote) {
    return false;
  }
  const remoteName = `origin/${deleteTarget.value.name}`;
  return branches.value.some((branch) => branch.isRemote && branch.name === remoteName);
});

const deleteQuestion = computed(() =>
  t("repo.deleteBranchQuestion", { name: deleteTarget.value?.name ?? "" }).replace(
    /<\/?name>/g,
    "",
  ),
);

const tableCols = computed(() =>
  scope.value === "local"
    ? "grid-cols-[minmax(0,1.1fr)_minmax(0,1.5fr)_5.5rem_9rem_minmax(0,6rem)_4rem_2.25rem]"
    : "grid-cols-[minmax(0,1.4fr)_5.5rem_9rem_minmax(0,7rem)_4rem_2.25rem]",
);

const scopeOptions = computed(() => [
  { id: "local" as const, label: t("branchManage.scopeLocal") },
  { id: "remote" as const, label: t("branchManage.scopeRemote") },
]);

const activityOptions = computed(() => [
  { id: "all" as const, label: `${t("branchManage.filterAll")} (${activityCounts.value.all})` },
  {
    id: "active" as const,
    label: `${t("branchManage.filterActive")} (${activityCounts.value.active})`,
  },
  {
    id: "inactive" as const,
    label: `${t("branchManage.filterInactive")} (${activityCounts.value.inactive})`,
  },
]);

async function loadBranches(): Promise<void> {
  branches.value = await listBranches(props.project.path, true);
}

watch(
  () => props.project.path,
  (_path, _previous, onCleanup) => {
    let active = true;
    loading.value = true;
    error.value = null;
    void loadBranches()
      .catch((reason: unknown) => {
        if (active) {
          error.value = toUserMessage(reason) || t("branchManage.loadFailed");
          branches.value = [];
        }
      })
      .finally(() => {
        if (active) {
          loading.value = false;
        }
      });
    onCleanup(() => {
      active = false;
    });
  },
  { immediate: true },
);

async function handleRefresh(): Promise<void> {
  refreshing.value = true;
  try {
    await loadBranches();
  } catch (reason: unknown) {
    message.error(toUserMessage(reason) || t("branchManage.refreshFailed"));
  } finally {
    refreshing.value = false;
  }
}

function openDelete(branch: GitBranch): void {
  if (branch.isRemote || branch.isCurrent) {
    return;
  }
  deleteTarget.value = branch;
  deleteRemoteAlso.value = false;
}

async function confirmDelete(): Promise<void> {
  if (!deleteTarget.value || deleteBusy.value) {
    return;
  }
  const targetName = deleteTarget.value.name;
  const alsoRemote = deleteHasRemote.value && deleteRemoteAlso.value;
  deleteBusy.value = true;
  try {
    await deleteBranch(props.project.path, targetName, {
      force: true,
      deleteRemote: alsoRemote,
      remote: "origin",
    });
    deleteTarget.value = null;
    deleteRemoteAlso.value = false;
    await loadBranches();
    message.success(t("repo.deleteBranchSuccess", { name: targetName }));
  } catch (reason: unknown) {
    message.error(toUserMessage(reason) || t("branchManage.deleteFailed"));
  } finally {
    deleteBusy.value = false;
  }
}

function compareByTime(left: GitBranch, right: GitBranch, direction: SortDirection): number {
  const leftMs = parseAuthoredMs(left.tipAuthoredAt);
  const rightMs = parseAuthoredMs(right.tipAuthoredAt);
  if (leftMs === rightMs) {
    return left.name.localeCompare(right.name);
  }
  if (leftMs === null) {
    return 1;
  }
  if (rightMs === null) {
    return -1;
  }
  return direction === "desc" ? rightMs - leftMs : leftMs - rightMs;
}

function parseAuthoredMs(value: string): number | null {
  const trimmed = value.trim();
  if (!trimmed) {
    return null;
  }
  const parsed = dayjs(trimmed);
  return parsed.isValid() ? parsed.valueOf() : null;
}

function statusLabel(branch: GitBranch): string {
  if (!branch.tipAuthoredAt.trim()) {
    return t("branchManage.statusUnknown");
  }
  return isBranchActive(branch.tipAuthoredAt)
    ? t("branchManage.statusActive")
    : t("branchManage.statusInactive");
}

function deleteDisabledTitle(branch: GitBranch): string {
  if (branch.isCurrent) {
    return t("branchManage.deleteCurrentDisabled");
  }
  if (branch.isRemote) {
    return t("branchManage.deleteRemoteDisabled");
  }
  return t("repo.deleteBranchAction");
}
</script>

<template>
  <AppLoadingScreen v-if="loading" />
  <main
    v-else
    class="bg-background text-foreground flex h-screen min-h-0 w-full flex-col overflow-hidden"
  >
    <AppWindowHeader height-class-name="h-11">
      <span class="truncate text-sm font-semibold">{{ t("branchManage.windowTitle") }}</span>
    </AppWindowHeader>

    <div class="border-border flex shrink-0 flex-wrap items-center gap-2 border-b px-3 py-2">
      <div class="bg-muted/60 flex gap-0.5 rounded-md p-0.5" role="radiogroup">
        <button
          v-for="item in scopeOptions"
          :key="item.id"
          type="button"
          role="radio"
          :aria-checked="scope === item.id"
          :class="
            cn(
              'rounded px-2 py-1 text-[11px]',
              scope === item.id ? 'bg-background shadow-xs' : 'text-muted-foreground',
            )
          "
          @click="scope = item.id"
        >
          {{ item.label }}
        </button>
      </div>
      <div class="bg-muted/60 flex gap-0.5 rounded-md p-0.5" role="radiogroup">
        <button
          v-for="item in activityOptions"
          :key="item.id"
          type="button"
          role="radio"
          :aria-checked="activity === item.id"
          :class="
            cn(
              'rounded px-2 py-1 text-[11px]',
              activity === item.id ? 'bg-background shadow-xs' : 'text-muted-foreground',
            )
          "
          @click="activity = item.id"
        >
          {{ item.label }}
        </button>
      </div>
      <div class="ml-auto flex items-center gap-1.5">
        <Input
          v-model:value="search"
          size="small"
          class="w-52"
          :placeholder="t('branchManage.searchPlaceholder')"
          :aria-label="t('branchManage.searchPlaceholder')"
        />
        <Tooltip :title="t('repo.refresh')">
          <Button
            size="small"
            :aria-label="t('repo.refresh')"
            :disabled="loading || refreshing"
            :loading="refreshing"
            @click="void handleRefresh()"
          >
            <Icon name="RefreshCw" :size="14" />
          </Button>
        </Tooltip>
      </div>
    </div>

    <p
      v-if="error"
      class="text-destructive flex flex-1 items-center justify-center px-4 text-center text-sm"
    >
      {{ error }}
    </p>
    <Empty
      v-else-if="!loading && visibleBranches.length === 0"
      class="flex-1"
      :description="t('branchManage.emptyDescription')"
    >
      <template #image>
        <Icon name="GitBranch" :size="28" class="text-muted-foreground" />
      </template>
      <p class="text-sm font-medium">{{ t("branchManage.empty") }}</p>
    </Empty>
    <div v-else class="flex min-h-0 flex-1 flex-col">
      <div
        :class="
          cn(
            'border-border bg-muted/30 text-muted-foreground grid shrink-0 items-center gap-2 border-b px-3 py-1.5 text-[11px] font-medium',
            tableCols,
          )
        "
      >
        <span>{{ t("branchManage.columnBranch") }}</span>
        <span v-if="scope === 'local'">{{ t("branchManage.columnTracking") }}</span>
        <span>{{ t("branchManage.columnCommit") }}</span>
        <button
          type="button"
          class="hover:text-foreground inline-flex items-center gap-0.5 text-left"
          :aria-label="
            sortDir === 'desc' ? t('branchManage.sortTimeDesc') : t('branchManage.sortTimeAsc')
          "
          @click="sortDir = sortDir === 'desc' ? 'asc' : 'desc'"
        >
          {{ t("branchManage.columnTime") }}
          <Icon :name="sortDir === 'desc' ? 'ArrowDown' : 'ArrowUp'" :size="12" />
        </button>
        <span>{{ t("branchManage.columnAuthor") }}</span>
        <span>{{ t("branchManage.columnStatus") }}</span>
        <span class="text-right">{{ t("branchManage.columnActions") }}</span>
      </div>
      <ScrollArea class="min-h-0 flex-1">
        <div
          v-for="branch in visibleBranches"
          :key="branch.name"
          :class="cn('grid items-center gap-2 px-3 py-1.5 text-xs', tableCols)"
        >
          <span class="flex min-w-0 items-center gap-1">
            <HighlightText :text="branch.name" :query="search" class-name="truncate font-mono" />
            <Tag v-if="branch.isCurrent" class="shrink-0 text-[10px]">
              {{ t("branchManage.currentBranch") }}
            </Tag>
            <Tag v-else-if="branch.isDefault" class="shrink-0 text-[10px]">
              {{ t("branchManage.defaultBranch") }}
            </Tag>
          </span>
          <span v-if="scope === 'local'" class="text-muted-foreground truncate font-mono">
            {{ branch.upstream || t("branchManage.noTracking") }}
          </span>
          <span class="font-mono">{{
            branch.tipShortId.trim() || t("branchManage.noCommit")
          }}</span>
          <span class="tabular-nums">
            {{ formatCommitDateTime(branch.tipAuthoredAt) || t("branchManage.noCommit") }}
          </span>
          <span class="truncate">{{ branch.tipAuthorName }}</span>
          <span>{{ statusLabel(branch) }}</span>
          <Tooltip :title="deleteDisabledTitle(branch)">
            <Button
              size="small"
              type="text"
              danger
              :aria-label="t('repo.deleteBranchAction')"
              :disabled="branch.isRemote || branch.isCurrent"
              @click="openDelete(branch)"
            >
              <Icon name="Trash2" :size="12" />
            </Button>
          </Tooltip>
        </div>
      </ScrollArea>
    </div>

    <Modal
      :open="Boolean(deleteTarget)"
      :title="t('repo.deleteBranchTitle')"
      :ok-text="t('repo.deleteBranchAction')"
      :cancel-text="t('common.cancel')"
      ok-type="danger"
      :confirm-loading="deleteBusy"
      @update:open="(open: boolean) => !open && !deleteBusy && (deleteTarget = null)"
      @ok="void confirmDelete()"
    >
      <p class="text-sm">{{ deleteQuestion }}</p>
      <label v-if="deleteHasRemote" class="mt-3 flex items-center gap-2 text-sm">
        <Checkbox v-model:checked="deleteRemoteAlso" :disabled="deleteBusy" />
        {{ t("repo.deleteBranchRemoteCheckbox") }}
      </label>
    </Modal>
  </main>
</template>

// src/components/git/BranchManageWorkspace.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import dayjs from "dayjs";
import { GitBranch as GitBranchIcon, RefreshCw, Search, TriangleAlert } from "lucide-react";
import { Trans, useTranslation } from "react-i18next";
import { toast } from "sonner";

import { AppLoadingScreen } from "@/components/common/AppLoadingScreen";
import { EmptyState } from "@/components/common/EmptyState";
import {
  BranchManageTable,
  type BranchManageSortDirection,
} from "@/components/git/BranchManageTable";
import { AppWindowHeader } from "@/components/layout/AppWindowHeader";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { AppDialogContent } from "@/components/common/AppDialogContent";
import { Dialog, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field, FieldContent, FieldDescription, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Spinner } from "@/components/ui/spinner";
import { cn } from "@/lib/utils";
import { deleteBranch, listBranches } from "@/services/git/git.branch";
import { toUserMessage } from "@/types/error";
import type { GitBranch } from "@/types/git";
import type { Project } from "@/types/project";
import { isBranchActive } from "@/utils/branchActivity";
import { deferUi } from "@/utils/deferUi";

type ScopeFilter = "local" | "remote";
type ActivityFilter = "all" | "active" | "inactive";

interface BranchManageWorkspaceProps {
  project: Project;
}

function SegmentedControl<T extends string>({
  value,
  options,
  ariaLabel,
  onChange,
}: {
  value: T;
  options: { value: T; label: string }[];
  ariaLabel: string;
  onChange: (value: T) => void;
}) {
  return (
    <div
      className="bg-muted/60 flex flex-wrap gap-0.5 rounded-md p-0.5"
      role="radiogroup"
      aria-label={ariaLabel}
    >
      {options.map((option) => {
        const selected = value === option.value;
        return (
          <button
            key={option.value}
            type="button"
            role="radio"
            aria-checked={selected}
            className={cn(
              "hover:bg-background/80 min-w-0 cursor-pointer rounded px-2 py-1 text-[11px] transition-colors",
              selected ? "bg-background text-foreground shadow-xs" : "text-muted-foreground",
            )}
            onClick={() => onChange(option.value)}
          >
            {option.label}
          </button>
        );
      })}
    </div>
  );
}

/** 分支管理子弹窗：只读列表 + 筛选/排序 */
export function BranchManageWorkspace({ project }: BranchManageWorkspaceProps) {
  const { t } = useTranslation();
  const [branches, setBranches] = useState<GitBranch[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [scope, setScope] = useState<ScopeFilter>("local");
  const [activity, setActivity] = useState<ActivityFilter>("all");
  const [search, setSearch] = useState("");
  const [sortDir, setSortDir] = useState<BranchManageSortDirection>("desc");
  const [deleteTarget, setDeleteTarget] = useState<GitBranch | null>(null);
  const [deleteRemoteAlso, setDeleteRemoteAlso] = useState(false);
  const [deleteBusy, setDeleteBusy] = useState(false);
  const [deletingName, setDeletingName] = useState<string | null>(null);

  const loadBranches = useCallback(async () => {
    const result = await listBranches(project.path, true);
    setBranches(result);
    return result;
  }, [project.path]);

  useEffect(() => {
    let active = true;
    setLoading(true);
    setError(null);
    void loadBranches()
      .catch((reason: unknown) => {
        if (active) {
          setError(toUserMessage(reason) || t("branchManage.loadFailed"));
          setBranches([]);
        }
      })
      .finally(() => {
        if (active) setLoading(false);
      });
    return () => {
      active = false;
    };
  }, [loadBranches, t]);

  const scopedBranches = useMemo(
    () => branches.filter((branch) => (scope === "local" ? !branch.isRemote : branch.isRemote)),
    [branches, scope],
  );

  const activityCounts = useMemo(() => {
    let activeCount = 0;
    let inactiveCount = 0;
    for (const branch of scopedBranches) {
      if (isBranchActive(branch.tipAuthoredAt)) {
        activeCount += 1;
      } else {
        inactiveCount += 1;
      }
    }
    return {
      all: scopedBranches.length,
      active: activeCount,
      inactive: inactiveCount,
    };
  }, [scopedBranches]);

  const searchLower = search.trim().toLowerCase();

  const visibleBranches = useMemo(() => {
    let next = scopedBranches;
    if (activity === "active") {
      next = next.filter((branch) => isBranchActive(branch.tipAuthoredAt));
    } else if (activity === "inactive") {
      next = next.filter((branch) => !isBranchActive(branch.tipAuthoredAt));
    }
    if (searchLower) {
      next = next.filter((branch) => {
        const haystack =
          `${branch.name} ${branch.upstream ?? ""} ${branch.tipShortId} ${branch.tipAuthorName}`.toLowerCase();
        return haystack.includes(searchLower);
      });
    }
    return [...next].sort((left, right) => compareByTime(left, right, sortDir));
  }, [activity, scopedBranches, searchLower, sortDir]);

  async function handleRefresh(): Promise<void> {
    setRefreshing(true);
    try {
      await loadBranches();
      toast.success(t("branchManage.refreshSuccess"));
    } catch (reason: unknown) {
      toast.error(toUserMessage(reason) || t("branchManage.refreshFailed"));
    } finally {
      setRefreshing(false);
    }
  }

  const deleteHasRemote = useMemo(() => {
    if (!deleteTarget || deleteTarget.isRemote) {
      return false;
    }
    const remoteName = `origin/${deleteTarget.name}`;
    return branches.some((branch) => branch.isRemote && branch.name === remoteName);
  }, [branches, deleteTarget]);

  function openDelete(branch: GitBranch): void {
    if (branch.isRemote || branch.isCurrent) {
      return;
    }
    deferUi(() => {
      setDeleteTarget(branch);
      setDeleteRemoteAlso(false);
      setDeleteBusy(false);
    });
  }

  async function confirmDelete(): Promise<void> {
    if (!deleteTarget || deleteBusy) {
      return;
    }
    const targetName = deleteTarget.name;
    const alsoRemote = deleteHasRemote && deleteRemoteAlso;

    setDeleteBusy(true);
    setDeletingName(targetName);
    try {
      await deleteBranch(project.path, targetName, {
        force: true,
        deleteRemote: alsoRemote,
        remote: "origin",
      });
      setDeleteTarget(null);
      setDeleteRemoteAlso(false);
      await loadBranches();
      toast.success(t("repo.deleteBranchSuccess", { name: targetName }));
    } catch (reason: unknown) {
      toast.error(toUserMessage(reason) || t("branchManage.deleteFailed"));
    } finally {
      setDeleteBusy(false);
      setDeletingName(null);
    }
  }

  if (loading) {
    return <AppLoadingScreen />;
  }

  return (
    <main className="bg-background text-foreground flex h-screen min-h-0 w-full flex-col overflow-hidden">
      <AppWindowHeader heightClassName="h-11">
        <span className="truncate text-sm font-semibold">{t("branchManage.windowTitle")}</span>
      </AppWindowHeader>

      <div className="border-border flex shrink-0 flex-wrap items-center gap-2 border-b px-3 py-2">
        <SegmentedControl
          value={scope}
          ariaLabel={t("branchManage.scopeLocal")}
          options={[
            { value: "local", label: t("branchManage.scopeLocal") },
            { value: "remote", label: t("branchManage.scopeRemote") },
          ]}
          onChange={setScope}
        />

        <SegmentedControl
          value={activity}
          ariaLabel={t("branchManage.filterAll")}
          options={[
            {
              value: "all",
              label: `${t("branchManage.filterAll")} (${activityCounts.all})`,
            },
            {
              value: "active",
              label: `${t("branchManage.filterActive")} (${activityCounts.active})`,
            },
            {
              value: "inactive",
              label: `${t("branchManage.filterInactive")} (${activityCounts.inactive})`,
            },
          ]}
          onChange={setActivity}
        />

        <div className="ml-auto flex items-center gap-1.5">
          <div className="relative">
            <Search
              className="text-muted-foreground pointer-events-none absolute top-1/2 left-2 size-3.5 -translate-y-1/2"
              aria-hidden="true"
            />
            <Input
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder={t("branchManage.searchPlaceholder")}
              className="h-7 w-52 pl-7 text-xs shadow-none"
              aria-label={t("branchManage.searchPlaceholder")}
            />
          </div>

          <Button
            type="button"
            variant="outline"
            size="icon"
            className="size-7 shrink-0 [&_svg]:size-3.5"
            aria-label={t("repo.refresh")}
            disabled={loading || refreshing}
            onClick={() => void handleRefresh()}
          >
            {refreshing ? <Spinner className="size-3.5" /> : <RefreshCw aria-hidden="true" />}
          </Button>
        </div>
      </div>

      {error ? (
        <p className="text-destructive flex flex-1 items-center justify-center px-4 text-center text-sm">
          {error}
        </p>
      ) : null}
      {!error && visibleBranches.length === 0 ? (
        <EmptyState
          compact
          className="min-h-0 flex-1"
          icon={<GitBranchIcon />}
          title={t("branchManage.empty")}
          description={t("branchManage.emptyDescription")}
        />
      ) : null}
      {!error && visibleBranches.length > 0 ? (
        <BranchManageTable
          branches={visibleBranches}
          sortDir={sortDir}
          onToggleSort={() => setSortDir((prev) => (prev === "desc" ? "asc" : "desc"))}
          onDelete={openDelete}
          deletingName={deletingName}
          showTracking={scope === "local"}
        />
      ) : null}

      <Dialog
        open={Boolean(deleteTarget)}
        onOpenChange={(open) => {
          if (!open && !deleteBusy) {
            setDeleteTarget(null);
          }
        }}
      >
        <AppDialogContent>
          <DialogHeader>
            <DialogTitle>{t("repo.deleteBranchTitle")}</DialogTitle>
          </DialogHeader>

          <div className="flex gap-3">
            <TriangleAlert className="text-chart-4 mt-0.5 size-5 shrink-0" aria-hidden="true" />
            <div className="min-w-0 flex-1 space-y-3">
              <div className="space-y-1">
                <p className="text-foreground text-sm">
                  <Trans
                    i18nKey="repo.deleteBranchQuestion"
                    values={{ name: deleteTarget?.name ?? "" }}
                    components={{
                      name: <span className="font-mono font-medium" />,
                    }}
                  />
                </p>
                <p className="text-muted-foreground text-xs">
                  {t("repo.deleteBranchIrreversible")}
                </p>
              </div>

              {deleteHasRemote ? (
                <Field orientation="horizontal">
                  <Checkbox
                    id="manage-delete-branch-remote"
                    checked={deleteRemoteAlso}
                    onCheckedChange={(checked) => setDeleteRemoteAlso(checked === true)}
                    disabled={deleteBusy}
                  />
                  <FieldContent>
                    <FieldLabel htmlFor="manage-delete-branch-remote">
                      {t("repo.deleteBranchRemoteCheckbox")}
                    </FieldLabel>
                    <FieldDescription>{t("repo.deleteBranchRemoteHint")}</FieldDescription>
                  </FieldContent>
                </Field>
              ) : null}
            </div>
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              disabled={deleteBusy}
              onClick={() => setDeleteTarget(null)}
            >
              {t("common.cancel")}
            </Button>
            <Button
              type="button"
              variant="destructive"
              disabled={deleteBusy}
              onClick={() => void confirmDelete()}
            >
              {deleteBusy ? <Spinner className="size-3.5" /> : null}
              {t("repo.deleteBranchAction")}
            </Button>
          </DialogFooter>
        </AppDialogContent>
      </Dialog>
    </main>
  );
}

function compareByTime(
  left: GitBranch,
  right: GitBranch,
  direction: BranchManageSortDirection,
): number {
  const leftMs = parseAuthoredMs(left.tipAuthoredAt);
  const rightMs = parseAuthoredMs(right.tipAuthoredAt);
  if (leftMs === rightMs) {
    return left.name.localeCompare(right.name);
  }
  if (leftMs === null) return 1;
  if (rightMs === null) return -1;
  return direction === "desc" ? rightMs - leftMs : leftMs - rightMs;
}

function parseAuthoredMs(value: string): number | null {
  const trimmed = value.trim();
  if (!trimmed) return null;
  const parsed = dayjs(trimmed);
  return parsed.isValid() ? parsed.valueOf() : null;
}
