// src/components/Git/src/BranchCompareWorkspace.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";

import { Button, Empty, Input, Select, Tooltip } from "antdv-next";
import { useI18n } from "vue-i18n";

import MaterialFileIcon from "./MaterialFileIcon.vue";
import { Icon } from "@/components/Icon";
import AppWindowHeader from "@/layouts/page/AppWindowHeader.vue";
import ResizableSplit from "@/layouts/default/components/ResizableSplit.vue";
import { ScrollArea } from "@/components/ScrollArea";
import { cn } from "@/lib/utils";
import { getBranchCompare, getBranchFileDiff, getCommit, getLog } from "@/services/git";
import { toUserMessage } from "@/types/error";
import type {
  BranchCompareMode,
  GitBranch,
  GitChangedFile,
  GitCommitDetail,
  GitCommitSummary,
  GitDiffResult,
} from "@/types/git";
import type { Project } from "@/types/project";
import { gitStatusLetterClass } from "@/utils/gitStatusStyle";
import { DEFAULT_TEXT_ENCODING } from "@/utils/textEncodings";

defineOptions({ name: "BranchCompareWorkspace" });

const props = defineProps<{
  project: Project;
  branches: GitBranch[];
  initialMode: BranchCompareMode;
  initialBase: string;
  initialTarget: string;
}>();

type CompareView = "files" | "commits";

const { t } = useI18n();
const localBranches = computed(() => props.branches.filter((branch) => !branch.isRemote));
const currentBranch =
  props.branches.find((branch) => branch.isCurrent)?.name ?? localBranches.value[0]?.name ?? "";
const mode = ref<BranchCompareMode>(props.initialMode);
const base = ref(props.initialBase || currentBranch);
const target = ref(props.initialTarget);
const view = ref<CompareView>("files");
const files = ref<GitChangedFile[] | null>(null);
const selectedPath = ref<string | null>(null);
const fileFilter = ref("");
const fileError = ref<string | null>(null);
const diff = ref<GitDiffResult | null>(null);
const diffError = ref<string | null>(null);
const commitLists = ref<{
  baseOnly: GitCommitSummary[];
  targetOnly: GitCommitSummary[];
} | null>(null);
const selectedCommit = ref<GitCommitDetail | null>(null);
const loadingFiles = ref(false);
const loadingDiff = ref(false);

const upstream = computed(
  () => localBranches.value.find((branch) => branch.name === base.value)?.upstream ?? "",
);
const effectiveTarget = computed(() =>
  mode.value === "localUpstream" ? upstream.value : target.value,
);
const visibleFiles = computed(
  () =>
    files.value?.filter((file) =>
      file.path.toLowerCase().includes(fileFilter.value.trim().toLowerCase()),
    ) ?? [],
);
const summary = computed(() => summarizeFiles(files.value ?? []));

const modeOptions = computed(() => [
  { value: "branch", label: t("branchCompare.modeBranch") },
  { value: "localUpstream", label: t("branchCompare.modeLocalUpstream") },
]);
const sourceOptions = computed(() =>
  (mode.value === "localUpstream" ? localBranches.value : props.branches).map((branch) => ({
    value: branch.name,
    label: branch.name,
  })),
);
const targetOptions = computed(() =>
  props.branches.map((branch) => ({ value: branch.name, label: branch.name })),
);
const viewOptions = computed(() => [
  { id: "files" as const, label: t("branchCompare.files") },
  { id: "commits" as const, label: t("branchCompare.commits") },
]);

function setMode(next: unknown): void {
  mode.value = next === "localUpstream" ? "localUpstream" : "branch";
}

watch([mode, upstream], () => {
  if (mode.value === "localUpstream") {
    target.value = upstream.value;
  }
});

watch(
  () => [props.project.path, base.value, effectiveTarget.value, view.value] as const,
  ([path, nextBase, nextTarget, nextView], _previous, onCleanup) => {
    files.value = null;
    selectedPath.value = null;
    diff.value = null;
    fileError.value = null;
    commitLists.value = null;
    selectedCommit.value = null;
    if (!nextBase || !nextTarget) {
      return;
    }
    let cancelled = false;
    loadingFiles.value = true;
    if (nextView === "files") {
      void getBranchCompare(path, { base: nextBase, target: nextTarget })
        .then((result) => {
          if (cancelled) {
            return;
          }
          files.value = result.files;
          selectedPath.value = result.files[0]?.path ?? null;
        })
        .catch((reason: unknown) => {
          if (!cancelled) {
            fileError.value = toUserMessage(reason) || t("branchCompare.loadFilesFailed");
          }
        })
        .finally(() => {
          if (!cancelled) {
            loadingFiles.value = false;
          }
        });
    } else {
      void Promise.all([
        getLog(path, { ref: `${nextTarget}..${nextBase}`, limit: 100 }),
        getLog(path, { ref: `${nextBase}..${nextTarget}`, limit: 100 }),
      ])
        .then(([baseOnly, targetOnly]) => {
          if (!cancelled) {
            commitLists.value = { baseOnly: baseOnly.commits, targetOnly: targetOnly.commits };
          }
        })
        .catch((reason: unknown) => {
          if (!cancelled) {
            fileError.value = toUserMessage(reason) || t("branchCompare.loadCommitsFailed");
          }
        })
        .finally(() => {
          if (!cancelled) {
            loadingFiles.value = false;
          }
        });
    }
    onCleanup(() => {
      cancelled = true;
    });
  },
  { immediate: true },
);

watch(
  () => [props.project.path, selectedPath.value, base.value, effectiveTarget.value] as const,
  ([path, nextPath, nextBase, nextTarget], _previous, onCleanup) => {
    diff.value = null;
    diffError.value = null;
    if (!nextPath || !nextBase || !nextTarget) {
      loadingDiff.value = false;
      return;
    }
    let cancelled = false;
    loadingDiff.value = true;
    void getBranchFileDiff(path, {
      base: nextBase,
      target: nextTarget,
      filePath: nextPath,
      encoding: DEFAULT_TEXT_ENCODING,
    })
      .then((result) => {
        if (!cancelled) {
          diff.value = result;
        }
      })
      .catch((reason: unknown) => {
        if (!cancelled) {
          diffError.value = toUserMessage(reason) || t("branchCompare.loadDiffFailed");
        }
      })
      .finally(() => {
        if (!cancelled) {
          loadingDiff.value = false;
        }
      });
    onCleanup(() => {
      cancelled = true;
    });
  },
  { immediate: true },
);

function selectLocalBranch(nextBase: string): void {
  base.value = nextBase;
  if (mode.value === "localUpstream") {
    target.value = localBranches.value.find((branch) => branch.name === nextBase)?.upstream ?? "";
  }
}

function handleSourceChange(next: unknown): void {
  const value = String(next ?? "");
  if (mode.value === "localUpstream") {
    selectLocalBranch(value);
    return;
  }
  base.value = value;
}

function swapRefs(): void {
  const previousBase = base.value;
  base.value = effectiveTarget.value;
  target.value = previousBase;
}

async function selectCommit(commit: GitCommitSummary): Promise<void> {
  selectedCommit.value = null;
  try {
    selectedCommit.value = (await getCommit(props.project.path, commit.id)).commit;
  } catch (reason: unknown) {
    fileError.value = toUserMessage(reason) || t("branchCompare.loadCommitFailed");
  }
}

function summarizeFiles(list: readonly GitChangedFile[]) {
  return {
    total: list.length,
    added: list.filter((file) => file.status === "A").length,
    modified: list.filter((file) => !["A", "D"].includes(file.status)).length,
    deleted: list.filter((file) => file.status === "D").length,
  };
}
</script>

<template>
  <main class="bg-background text-foreground flex h-screen min-h-0 w-full flex-col overflow-hidden">
    <AppWindowHeader>
      <span
        class="truncate text-sm font-semibold"
        :title="t('branchCompare.windowTitle', { path: project.path })"
      >
        {{ t("branchCompare.windowTitle", { path: project.path }) }}
      </span>
    </AppWindowHeader>
    <section class="border-border flex shrink-0 flex-wrap items-center gap-2 border-b px-4 py-2">
      <Icon name="GitCompareArrows" :size="18" class="shrink-0" />
      <Select :value="mode" class="w-44" :options="modeOptions" @update:value="setMode" />
      <span class="shrink-0 text-sm font-medium">{{ t("branchCompare.source") }}</span>
      <Select
        :value="base"
        class="min-w-40 flex-1"
        :options="sourceOptions"
        @update:value="handleSourceChange"
      />
      <Tooltip :title="t('branchCompare.swap')">
        <Button size="small" :disabled="mode === 'localUpstream'" @click="swapRefs">
          <template #icon>
            <Icon name="ArrowLeftRight" :size="14" />
          </template>
        </Button>
      </Tooltip>
      <span class="shrink-0 text-sm font-medium">{{ t("branchCompare.target") }}</span>
      <Select
        :value="effectiveTarget"
        class="min-w-40 flex-1"
        :options="targetOptions"
        :disabled="mode === 'localUpstream'"
        @update:value="(next) => (target = String(next ?? ''))"
      />
      <div class="border-border flex rounded-md border p-0.5" role="tablist">
        <button
          v-for="item in viewOptions"
          :key="item.id"
          type="button"
          role="tab"
          :aria-selected="view === item.id"
          :class="
            cn(
              'rounded px-3 py-1 text-sm',
              view === item.id && 'bg-primary text-primary-foreground',
            )
          "
          @click="view = item.id"
        >
          {{ item.label }}
        </button>
      </div>
    </section>
    <p
      v-if="mode === 'localUpstream' && !effectiveTarget"
      class="border-border text-muted-foreground shrink-0 border-b px-4 py-2 text-xs"
    >
      {{ t("branchCompare.noUpstream") }}
    </p>
    <ResizableSplit
      v-if="view === 'files'"
      orientation="horizontal"
      :default-ratio="25"
      :min-first-px="200"
      :min-second-px="420"
      storage-key="jlgit:split:branch-compare-files"
    >
      <template #first>
        <aside class="flex h-full min-h-0 flex-col">
          <div class="border-border border-b px-3 py-2 text-xs font-medium">
            {{ t("branchCompare.changedFiles", summary) }}
          </div>
          <div class="p-2">
            <Input
              v-model:value="fileFilter"
              size="small"
              :placeholder="t('branchCompare.filterFiles')"
            />
          </div>
          <ScrollArea class="min-h-0 flex-1">
            <p v-if="fileError" class="text-destructive p-3 text-xs">{{ fileError }}</p>
            <p v-else-if="loadingFiles" class="text-muted-foreground p-3 text-xs">
              {{ t("branchCompare.loading") }}
            </p>
            <template v-else-if="visibleFiles.length">
              <button
                v-for="file in visibleFiles"
                :key="file.path"
                type="button"
                :class="
                  cn(
                    'flex h-7 w-full min-w-0 items-center gap-1 px-2 text-left text-xs',
                    selectedPath === file.path ? 'bg-accent' : 'hover:bg-accent/60',
                  )
                "
                @click="selectedPath = file.path"
              >
                <span
                  :class="
                    cn(
                      'w-3.5 shrink-0 text-center font-mono text-[11px] font-semibold',
                      gitStatusLetterClass(file.status),
                    )
                  "
                >
                  {{ file.status }}
                </span>
                <MaterialFileIcon :name="file.path" :is-dir="false" class-name="size-3.5" />
                <span class="min-w-0 flex-1 truncate" :title="file.path">{{ file.path }}</span>
              </button>
            </template>
            <Empty v-else :description="t('branchCompare.noFilesDescription')">
              <template #image>
                <Icon name="Files" :size="28" class="text-muted-foreground" />
              </template>
              <p class="text-sm">{{ t("branchCompare.noFiles") }}</p>
            </Empty>
          </ScrollArea>
        </aside>
      </template>
      <template #second>
        <section class="flex h-full min-h-0 flex-col">
          <p v-if="diffError" class="text-destructive p-4 text-sm">{{ diffError }}</p>
          <Empty
            v-else-if="!selectedPath"
            class="h-full"
            :description="t('branchCompare.selectFileDescription')"
          >
            <template #image>
              <Icon name="FileSearch" :size="28" class="text-muted-foreground" />
            </template>
            <p class="text-sm">{{ t("branchCompare.selectFile") }}</p>
          </Empty>
          <p v-else-if="loadingDiff || !diff" class="text-muted-foreground p-4 text-sm">
            {{ t("branchCompare.loading") }}
          </p>
          <p v-else-if="diff.binary" class="text-muted-foreground p-4 text-sm">
            {{ t("repo.diffBinary") }}
          </p>
          <ScrollArea v-else class="min-h-0 flex-1">
            <pre class="font-mono text-[11px] leading-5 whitespace-pre-wrap px-3 py-2">{{
              diff.patch || diff.newText || ""
            }}</pre>
          </ScrollArea>
        </section>
      </template>
    </ResizableSplit>
    <div
      v-else
      class="grid min-h-0 flex-1 grid-cols-[minmax(15rem,1fr)_minmax(15rem,1fr)_minmax(22rem,1.3fr)]"
    >
      <section class="border-border min-w-0 border-r">
        <h2 class="border-border truncate border-b px-3 py-2 text-sm font-medium">
          {{ t("branchCompare.baseOnly", { branch: base }) }}
        </h2>
        <ScrollArea class="h-[calc(100%-2.5rem)]">
          <button
            v-for="commit in commitLists?.baseOnly ?? []"
            :key="commit.id"
            type="button"
            class="hover:bg-accent/60 block w-full border-b px-3 py-2 text-left text-xs"
            @click="selectCommit(commit)"
          >
            <p class="text-muted-foreground font-mono">{{ commit.shortId }}</p>
            <p class="truncate">{{ commit.subject }}</p>
          </button>
          <p v-if="!commitLists?.baseOnly.length" class="text-muted-foreground p-3 text-xs">
            {{ t("branchCompare.noUniqueCommits") }}
          </p>
        </ScrollArea>
      </section>
      <section class="border-border min-w-0 border-r">
        <h2 class="border-border truncate border-b px-3 py-2 text-sm font-medium">
          {{ t("branchCompare.targetOnly", { branch: effectiveTarget }) }}
        </h2>
        <ScrollArea class="h-[calc(100%-2.5rem)]">
          <button
            v-for="commit in commitLists?.targetOnly ?? []"
            :key="commit.id"
            type="button"
            class="hover:bg-accent/60 block w-full border-b px-3 py-2 text-left text-xs"
            @click="selectCommit(commit)"
          >
            <p class="text-muted-foreground font-mono">{{ commit.shortId }}</p>
            <p class="truncate">{{ commit.subject }}</p>
          </button>
          <p v-if="!commitLists?.targetOnly.length" class="text-muted-foreground p-3 text-xs">
            {{ t("branchCompare.noUniqueCommits") }}
          </p>
        </ScrollArea>
      </section>
      <section class="min-w-0 p-4">
        <Empty
          v-if="!selectedCommit"
          class="h-full"
          :description="t('branchCompare.selectCommitDescription')"
        >
          <template #image>
            <Icon name="GitCommitHorizontal" :size="28" class="text-muted-foreground" />
          </template>
          <p class="text-sm">{{ t("branchCompare.selectCommit") }}</p>
        </Empty>
        <template v-else>
          <h2 class="text-sm font-semibold">{{ selectedCommit.subject }}</h2>
          <p class="text-muted-foreground mt-1 font-mono text-xs">{{ selectedCommit.id }}</p>
          <p class="text-muted-foreground mt-3 text-xs">
            {{ selectedCommit.authorName }} · {{ selectedCommit.authoredAt }}
          </p>
          <pre class="mt-4 text-xs whitespace-pre-wrap">{{ selectedCommit.body }}</pre>
        </template>
      </section>
    </div>
  </main>
</template>

// src/components/git/BranchCompareWorkspace.tsx
import { useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import {
  ArrowLeftRight,
  FileSearch,
  Files,
  GitCommitHorizontal,
  GitCompareArrows,
} from "lucide-react";
import { useTranslation } from "react-i18next";

import { MaterialFileIcon } from "@/components/git/MaterialFileIcon";
import { BranchCompareFilePreview } from "@/components/git/BranchCompareFilePreview";
import { DiffLineStats } from "@/components/git/DiffLineStats";
import { EmptyState } from "@/components/common/EmptyState";
import { TruncateStartPath } from "@/components/common/TruncateStartPath";
import { ResizableSplit } from "@/components/layout/ResizableSplit";
import { AppWindowHeader } from "@/components/layout/AppWindowHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { SelectMenu } from "@/components/common/SelectMenu";
import { getBranchCompare, getBranchFileDiff, getCommit, getLog } from "@/services/git";
import { cn } from "@/lib/utils";
import type {
  BranchCompareMode,
  GitBranch,
  GitChangedFile,
  GitCommitDetail,
  GitCommitSummary,
  GitDiffResult,
} from "@/types/git";
import type { Project } from "@/types/project";
import { toUserMessage } from "@/types/error";
import { gitStatusLetterClass } from "@/utils/gitStatusStyle";
import { DEFAULT_TEXT_ENCODING } from "@/utils/textEncodings";

interface BranchCompareWorkspaceProps {
  project: Project;
  branches: readonly GitBranch[];
  initialMode: BranchCompareMode;
  initialBase: string;
  initialTarget: string;
}

type CompareView = "files" | "commits";

const noDragStyle = { WebkitAppRegion: "no-drag" } as CSSProperties;

/** 只读分支比较的三段式工作区。 */
export function BranchCompareWorkspace({
  project,
  branches,
  initialMode,
  initialBase,
  initialTarget,
}: BranchCompareWorkspaceProps) {
  const { t } = useTranslation();
  const localBranches = useMemo(() => branches.filter((branch) => !branch.isRemote), [branches]);
  const allOptions = useMemo(
    () => branches.map((branch) => ({ value: branch.name, label: branch.name })),
    [branches],
  );
  const currentBranch =
    branches.find((branch) => branch.isCurrent)?.name ?? localBranches[0]?.name ?? "";
  const [mode, setMode] = useState<BranchCompareMode>(initialMode);
  const [base, setBase] = useState(initialBase || currentBranch);
  const [target, setTarget] = useState(initialTarget);
  const [view, setView] = useState<CompareView>("files");
  const [files, setFiles] = useState<GitChangedFile[] | null>(null);
  const [selectedPath, setSelectedPath] = useState<string | null>(null);
  const [fileFilter, setFileFilter] = useState("");
  const [fileError, setFileError] = useState<string | null>(null);
  const [diff, setDiff] = useState<GitDiffResult | null>(null);
  const [diffError, setDiffError] = useState<string | null>(null);
  const [encoding, setEncoding] = useState(DEFAULT_TEXT_ENCODING);
  const [commitLists, setCommitLists] = useState<{
    baseOnly: GitCommitSummary[];
    targetOnly: GitCommitSummary[];
  } | null>(null);
  const [selectedCommit, setSelectedCommit] = useState<GitCommitDetail | null>(null);
  const requestId = useRef(0);
  const diffRequestId = useRef(0);

  const upstream = localBranches.find((branch) => branch.name === base)?.upstream ?? "";
  const effectiveTarget = mode === "localUpstream" ? upstream : target;
  const visibleFiles = useMemo(
    () =>
      files?.filter((file) => file.path.toLowerCase().includes(fileFilter.trim().toLowerCase())) ??
      [],
    [fileFilter, files],
  );
  const summary = useMemo(() => summarizeFiles(files ?? []), [files]);

  useEffect(() => {
    if (mode === "localUpstream") {
      setTarget(upstream);
    }
  }, [mode, upstream]);

  useEffect(() => {
    const currentRequest = ++requestId.current;
    setFiles(null);
    setSelectedPath(null);
    setDiff(null);
    setFileError(null);
    setCommitLists(null);
    setSelectedCommit(null);
    if (!base || !effectiveTarget) return;
    if (view === "files") {
      void getBranchCompare(project.path, { base, target: effectiveTarget })
        .then((result) => {
          if (currentRequest !== requestId.current) return;
          setFiles(result.files);
          setSelectedPath(result.files[0]?.path ?? null);
        })
        .catch((reason: unknown) => {
          if (currentRequest === requestId.current)
            setFileError(toUserMessage(reason) || t("branchCompare.loadFilesFailed"));
        });
      return;
    }
    void Promise.all([
      getLog(project.path, { ref: `${effectiveTarget}..${base}`, limit: 100 }),
      getLog(project.path, { ref: `${base}..${effectiveTarget}`, limit: 100 }),
    ])
      .then(([baseOnly, targetOnly]) => {
        if (currentRequest === requestId.current)
          setCommitLists({ baseOnly: baseOnly.commits, targetOnly: targetOnly.commits });
      })
      .catch((reason: unknown) => {
        if (currentRequest === requestId.current)
          setFileError(toUserMessage(reason) || t("branchCompare.loadCommitsFailed"));
      });
  }, [base, effectiveTarget, project.path, t, view]);

  useEffect(() => {
    const currentRequest = ++diffRequestId.current;
    setDiff(null);
    setDiffError(null);
    if (!selectedPath || !base || !effectiveTarget) return;
    void getBranchFileDiff(project.path, {
      base,
      target: effectiveTarget,
      filePath: selectedPath,
      encoding,
    })
      .then((result) => {
        if (currentRequest === diffRequestId.current) setDiff(result);
      })
      .catch((reason: unknown) => {
        if (currentRequest === diffRequestId.current)
          setDiffError(toUserMessage(reason) || t("branchCompare.loadDiffFailed"));
      });
  }, [base, effectiveTarget, encoding, project.path, selectedPath, t]);

  function selectLocalBranch(nextBase: string): void {
    setBase(nextBase);
    if (mode === "localUpstream")
      setTarget(localBranches.find((branch) => branch.name === nextBase)?.upstream ?? "");
  }

  function swapRefs(): void {
    setBase(effectiveTarget);
    setTarget(base);
  }

  async function selectCommit(commit: GitCommitSummary): Promise<void> {
    setSelectedCommit(null);
    try {
      setSelectedCommit((await getCommit(project.path, commit.id)).commit);
    } catch (reason) {
      setFileError(toUserMessage(reason) || t("branchCompare.loadCommitFailed"));
    }
  }

  return (
    <main className="bg-background text-foreground flex h-screen min-h-0 w-full min-w-0 max-w-full flex-col overflow-hidden">
      <AppWindowHeader>
        <span
          className="truncate text-sm font-semibold"
          title={t("branchCompare.windowTitle", { path: project.path })}
        >
          {t("branchCompare.windowTitle", { path: project.path })}
        </span>
      </AppWindowHeader>
      <section
        className="border-border grid h-14 shrink-0 grid-cols-[auto_11rem_auto_minmax(0,1fr)_auto_auto_minmax(0,1fr)_auto] items-center gap-2 border-b px-4"
        style={noDragStyle}
      >
        <GitCompareArrows className="size-5 shrink-0" aria-hidden="true" />
        <SelectMenu
          value={mode}
          ariaLabel={t("branchCompare.title")}
          onChange={(value) => setMode(value as BranchCompareMode)}
          options={[
            { value: "branch", label: t("branchCompare.modeBranch") },
            { value: "localUpstream", label: t("branchCompare.modeLocalUpstream") },
          ]}
          triggerClassName="w-44"
        />
        <span className="shrink-0 whitespace-nowrap text-sm font-medium">
          {t("branchCompare.source")}
        </span>
        <SelectMenu
          value={base}
          ariaLabel={t("branchCompare.source")}
          onChange={mode === "localUpstream" ? selectLocalBranch : setBase}
          options={
            mode === "localUpstream"
              ? localBranches.map((branch) => ({ value: branch.name, label: branch.name }))
              : allOptions
          }
          triggerClassName="min-w-0 w-full"
        />
        <Button
          type="button"
          variant="ghost"
          size="icon"
          className="size-8 shrink-0"
          aria-label={t("branchCompare.swap")}
          disabled={mode === "localUpstream"}
          onClick={swapRefs}
        >
          <ArrowLeftRight className="size-4" />
        </Button>
        <span className="shrink-0 whitespace-nowrap text-sm font-medium">
          {t("branchCompare.target")}
        </span>
        <SelectMenu
          value={effectiveTarget}
          ariaLabel={t("branchCompare.target")}
          onChange={setTarget}
          disabled={mode === "localUpstream"}
          options={allOptions}
          triggerClassName="min-w-0 w-full"
        />
        <div className="flex shrink-0 items-center rounded-md border p-0.5 text-sm" role="tablist">
          {(["files", "commits"] as const).map((item) => (
            <button
              key={item}
              type="button"
              role="tab"
              aria-selected={view === item}
              onClick={() => setView(item)}
              className={cn(
                "rounded px-3 py-1",
                view === item && "bg-primary text-primary-foreground",
              )}
            >
              {t(`branchCompare.${item}`)}
            </button>
          ))}
        </div>
      </section>
      {mode === "localUpstream" && !effectiveTarget ? (
        <p className="border-border text-muted-foreground shrink-0 border-b px-4 py-2 text-xs">
          {t("branchCompare.noUpstream")}
        </p>
      ) : null}
      {view === "files" ? (
        <ResizableSplit
          orientation="horizontal"
          defaultRatio={25}
          minFirstPx={200}
          minSecondPx={420}
          storageKey="jlgit:split:branch-compare-files"
          first={
            <aside className="flex h-full min-h-0 flex-col">
              <div className="border-border border-b px-3 py-2 text-xs font-medium">
                {t("branchCompare.changedFiles", summary)}
              </div>
              <div className="p-2">
                <Input
                  className="h-8 text-xs"
                  value={fileFilter}
                  onChange={(event) => setFileFilter(event.target.value)}
                  placeholder={t("branchCompare.filterFiles")}
                />
              </div>
              <ScrollArea className="min-h-0 flex-1">
                {fileError ? (
                  <p className="text-destructive p-3 text-xs">{fileError}</p>
                ) : visibleFiles.length ? (
                  <div className="space-y-0.5 px-1 py-0.5">
                    {visibleFiles.map((file) => (
                      <button
                        type="button"
                        key={file.path}
                        onClick={() => setSelectedPath(file.path)}
                        className={cn(
                          "hover:bg-accent flex h-7 w-full min-w-0 items-center gap-1 rounded-md px-2 text-left text-xs transition-colors",
                          selectedPath === file.path && "bg-accent text-accent-foreground",
                        )}
                      >
                        <span
                          className={cn(
                            "w-3.5 shrink-0 text-center font-mono text-[11px] leading-none font-semibold",
                            gitStatusLetterClass(file.status),
                          )}
                        >
                          {file.status}
                        </span>
                        <MaterialFileIcon
                          name={file.path}
                          isDir={false}
                          className="size-3.5 shrink-0"
                        />
                        <TruncateStartPath
                          className="min-w-0 flex-1"
                          path={file.path}
                          highlightQuery={fileFilter}
                        />
                        <DiffLineStats
                          additions={file.additions}
                          deletions={file.deletions}
                          className="ml-0"
                        />
                      </button>
                    ))}
                  </div>
                ) : (
                  <EmptyState
                    compact
                    icon={<Files />}
                    title={t("branchCompare.noFiles")}
                    description={t("branchCompare.noFilesDescription")}
                  />
                )}
              </ScrollArea>
            </aside>
          }
          second={
            <section className="min-w-0 h-full">
              {diffError ? (
                <p className="text-destructive p-4 text-sm">{diffError}</p>
              ) : !selectedPath ? (
                <EmptyState
                  className="h-full"
                  icon={<FileSearch />}
                  title={t("branchCompare.selectFile")}
                  description={t("branchCompare.selectFileDescription")}
                />
              ) : !diff ? (
                <p className="text-muted-foreground p-4 text-sm">{t("branchCompare.loading")}</p>
              ) : (
                <BranchCompareFilePreview
                  repoPath={project.path}
                  base={base}
                  target={effectiveTarget}
                  path={selectedPath}
                  diff={diff}
                  encoding={encoding}
                  onEncodingChange={setEncoding}
                />
              )}
            </section>
          }
        />
      ) : (
        <div className="min-h-0 flex-1 grid grid-cols-[minmax(15rem,1fr)_minmax(15rem,1fr)_minmax(22rem,1.3fr)]">
          <CommitColumn
            title={t("branchCompare.baseOnly", { branch: base })}
            commits={commitLists?.baseOnly ?? []}
            onSelect={selectCommit}
          />
          <CommitColumn
            title={t("branchCompare.targetOnly", { branch: effectiveTarget })}
            commits={commitLists?.targetOnly ?? []}
            onSelect={selectCommit}
          />
          <CommitDetail commit={selectedCommit} />
        </div>
      )}
    </main>
  );
}

function CommitColumn({
  title,
  commits,
  onSelect,
}: {
  title: string;
  commits: readonly GitCommitSummary[];
  onSelect: (commit: GitCommitSummary) => void;
}) {
  const { t } = useTranslation();
  return (
    <section className="border-border min-w-0 border-r">
      <h2 className="border-border border-b px-3 py-2 text-sm font-medium truncate">{title}</h2>
      <ScrollArea className="h-[calc(100%-2.5rem)]">
        {commits.length ? (
          commits.map((commit) => (
            <button
              type="button"
              key={commit.id}
              onClick={() => void onSelect(commit)}
              className="hover:bg-accent block w-full border-b px-3 py-2 text-left text-xs"
            >
              <p className="text-muted-foreground font-mono">{commit.shortId}</p>
              <p className="truncate">{commit.subject}</p>
            </button>
          ))
        ) : (
          <EmptyState
            compact
            icon={<GitCommitHorizontal />}
            title={t("branchCompare.noUniqueCommits")}
          />
        )}
      </ScrollArea>
    </section>
  );
}

function CommitDetail({ commit }: { commit: GitCommitDetail | null }) {
  const { t } = useTranslation();
  return (
    <section className="min-w-0 h-full p-4">
      {!commit ? (
        <EmptyState
          className="h-full"
          icon={<GitCommitHorizontal />}
          title={t("branchCompare.selectCommit")}
          description={t("branchCompare.selectCommitDescription")}
        />
      ) : (
        <>
          <h2 className="text-sm font-semibold">{commit.subject}</h2>
          <p className="text-muted-foreground mt-1 font-mono text-xs">{commit.id}</p>
          <p className="text-muted-foreground mt-3 text-xs">
            {commit.authorName} · {commit.authoredAt}
          </p>
          <pre className="mt-4 whitespace-pre-wrap text-xs">{commit.body}</pre>
        </>
      )}
    </section>
  );
}
function summarizeFiles(files: readonly GitChangedFile[]) {
  return {
    total: files.length,
    added: files.filter((file) => file.status === "A").length,
    modified: files.filter((file) => !["A", "D"].includes(file.status)).length,
    deleted: files.filter((file) => file.status === "D").length,
  };
}
