// src/components/Ai/src/AgentReasoningBlock.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";

import { useI18n } from "vue-i18n";

import { Icon } from "@/components/Icon";
import { cn } from "@/lib/utils";

defineOptions({ name: "AgentReasoningBlock" });

const props = withDefaults(
  defineProps<{
    reasoning: string;
    isStreaming?: boolean;
    hasAnswer?: boolean;
    durationMs?: number;
  }>(),
  { isStreaming: false, hasAnswer: false, durationMs: undefined },
);

const { t } = useI18n();
const thinking = () => props.isStreaming && !props.hasAnswer;
const open = ref(thinking());
const autoCollapsed = ref(false);

watch(
  () => [props.isStreaming, props.hasAnswer] as const,
  () => {
    if (thinking()) {
      open.value = true;
      autoCollapsed.value = false;
      return;
    }
    if (props.hasAnswer && !autoCollapsed.value) {
      open.value = false;
      autoCollapsed.value = true;
    }
  },
);

const durationSeconds = computed(() =>
  props.durationMs != null && props.durationMs >= 0
    ? Math.max(1, Math.round(props.durationMs / 1000))
    : null,
);
</script>

<template>
  <div v-if="reasoning.trim()" :class="cn(hasAnswer && 'mb-1.5')">
    <button
      type="button"
      class="text-muted-foreground hover:text-foreground flex w-full cursor-pointer items-center gap-1 text-left text-[11px] leading-none font-medium"
      :aria-expanded="open"
      @click="open = !open"
    >
      <Icon
        name="ChevronRight"
        :size="14"
        :class="cn('shrink-0 transition-transform', open && 'rotate-90')"
      />
      <span v-if="thinking()" class="inline-flex items-center gap-1.5">
        <Icon name="LoaderCircle" :size="12" class="animate-spin" />
        {{ t("agent.deepThinking") }}
      </span>
      <span v-else>
        {{
          durationSeconds != null
            ? t("agent.deepThoughtDoneWithDuration", { seconds: durationSeconds })
            : t("agent.deepThoughtDone")
        }}
      </span>
    </button>
    <div
      v-if="open"
      class="text-muted-foreground border-border/70 mt-1.5 border-l-2 pl-2.5 text-[11px] leading-relaxed whitespace-pre-wrap"
    >
      {{ reasoning }}
    </div>
  </div>
</template>

// src/components/ai/AgentReasoningBlock.tsx
import { useEffect, useRef, useState } from "react";
import { ChevronRight, LoaderCircle } from "lucide-react";
import { useTranslation } from "react-i18next";

import { cn } from "@/lib/utils";

interface AgentReasoningBlockProps {
  reasoning: string;
  isStreaming: boolean;
  /** 是否已开始输出最终正文 */
  hasAnswer: boolean;
  /** 深度思考用时（毫秒） */
  durationMs?: number;
}

/**
 * DeepSeek 风格深度思考区：推理中默认展开，开始出正文后默认收起，可手动切换。
 */
export function AgentReasoningBlock({
  reasoning,
  isStreaming,
  hasAnswer,
  durationMs,
}: AgentReasoningBlockProps) {
  const { t } = useTranslation();
  const thinking = isStreaming && !hasAnswer;
  const [open, setOpen] = useState(thinking);
  const autoCollapsedRef = useRef(false);
  const durationSeconds =
    durationMs != null && durationMs >= 0
      ? Math.max(1, Math.round(durationMs / 1000))
      : null;

  useEffect(() => {
    if (thinking) {
      setOpen(true);
      autoCollapsedRef.current = false;
      return;
    }
    // 正文开始时只自动收起一次，避免覆盖用户手动展开
    if (hasAnswer && !autoCollapsedRef.current) {
      setOpen(false);
      autoCollapsedRef.current = true;
    }
  }, [thinking, hasAnswer]);

  if (!reasoning.trim()) {
    return null;
  }

  return (
    <div className={cn(hasAnswer && "mb-1.5")}>
      <button
        type="button"
        className="text-muted-foreground hover:text-foreground flex w-full cursor-pointer items-center gap-1 text-left text-[11px] leading-none font-medium"
        aria-expanded={open}
        onClick={() => setOpen((value) => !value)}
      >
        <ChevronRight
          className={cn(
            "size-3.5 shrink-0 transition-transform",
            open && "rotate-90",
          )}
          aria-hidden="true"
        />
        {thinking ? (
          <span className="inline-flex items-center gap-1.5">
            <LoaderCircle className="size-3 animate-spin" aria-hidden="true" />
            {t("agent.deepThinking")}
          </span>
        ) : (
          <span>
            {durationSeconds != null
              ? t("agent.deepThoughtDoneWithDuration", {
                  seconds: durationSeconds,
                })
              : t("agent.deepThoughtDone")}
          </span>
        )}
      </button>
      {open ? (
        <div className="text-muted-foreground border-border/70 mt-1.5 border-l-2 pl-2.5 text-[11px] leading-relaxed whitespace-pre-wrap">
          {reasoning}
          {thinking ? (
            <span
              className="bg-muted-foreground ml-0.5 inline-block h-2.5 w-0.5 animate-pulse align-middle"
              aria-hidden="true"
            />
          ) : null}
        </div>
      ) : null}
    </div>
  );
}
