// src/components/git/RepoOperationBanner.tsx
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { TriangleAlert } from "lucide-react";
import { toast } from "sonner";

import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { useRepoStore } from "@/store/useRepoStore";
import { toUserMessage } from "@/types/error";

function getOperationLabel(kind: string, translate: (key: string) => string): string {
  if (kind === "rebase") {
    return translate("repo.operationRebase");
  }
  if (kind === "cherryPick") {
    return translate("repo.operationCherryPick");
  }
  return translate("repo.operationMerge");
}

/** 仓库仍有 Git 序列操作时显示的常驻状态条。 */
export function RepoOperationBanner() {
  const { t } = useTranslation();
  const repoState = useRepoStore((state) => state.repoState);
  const abortOperation = useRepoStore((state) => state.abortOperation);
  const [aborting, setAborting] = useState(false);

  if (!repoState?.merging) {
    return null;
  }

  const operationLabel = getOperationLabel(repoState.kind, t);

  async function handleAbort(): Promise<void> {
    setAborting(true);
    try {
      await abortOperation();
      toast.success(t("repo.abortOperationSuccess"));
    } catch (error) {
      toast.error(toUserMessage(error));
    } finally {
      setAborting(false);
    }
  }

  return (
    <Alert className="min-h-8 rounded-none border-x-0 border-warning/35 bg-warning/15 px-3 py-1 text-xs text-warning-foreground">
      <TriangleAlert aria-hidden="true" />
      <div className="flex min-w-0 items-center gap-2">
        <span className="truncate font-medium">
          {t("repo.operationBanner", { operation: operationLabel })}
          {" · "}
          {repoState.conflictCount > 0
            ? t("repo.operationBannerConflict", { count: repoState.conflictCount })
            : t("repo.operationBannerReady")}
        </span>
        <Button
          type="button"
          variant="link"
          size="sm"
          disabled={aborting}
          className="h-auto shrink-0 px-0 text-xs text-warning-foreground underline-offset-4 hover:text-warning-foreground"
          onClick={() => void handleAbort()}
        >
          {aborting ? t("repo.abortOperationRunning") : t("repo.abortOperation")}
        </Button>
      </div>
    </Alert>
  );
}

// src/components/Git/src/RepoOperationBanner.vue
<script setup lang="ts">
import { computed, ref } from "vue";

import { Alert, Button, message } from "antdv-next";
import { useI18n } from "vue-i18n";

import { Icon } from "@/components/Icon";
import { useZustand } from "@/hooks/core/useZustand";
import { useRepoStore, useRepoStoreWithOut } from "@/store/modules/repo";
import { toUserMessage } from "@/types/error";

defineOptions({ name: "RepoOperationBanner" });

const { t } = useI18n();
const repoState = useZustand(useRepoStore, (state) => state.repoState);
const aborting = ref(false);

const visible = computed(() => Boolean(repoState.value?.merging));
const operationLabel = computed(() => {
  const kind = repoState.value?.kind;
  if (kind === "rebase") {
    return t("repo.operationRebase");
  }
  if (kind === "cherryPick") {
    return t("repo.operationCherryPick");
  }
  return t("repo.operationMerge");
});

async function handleAbort(): Promise<void> {
  aborting.value = true;
  try {
    await useRepoStoreWithOut().abortOperation();
    message.success(t("repo.abortOperationSuccess"));
  } catch (error) {
    message.error(toUserMessage(error));
  } finally {
    aborting.value = false;
  }
}
</script>

<template>
  <Alert
    v-if="visible && repoState"
    type="warning"
    show-icon
    banner
    class="rounded-none border-x-0 px-3 py-1 text-xs"
  >
    <template #icon>
      <Icon name="TriangleAlert" :size="14" />
    </template>
    <span class="truncate font-medium">
      {{ t("repo.operationBanner", { operation: operationLabel }) }}
      ·
      {{
        repoState.conflictCount > 0
          ? t("repo.operationBannerConflict", { count: repoState.conflictCount })
          : t("repo.operationBannerReady")
      }}
    </span>
    <template #action>
      <Button type="link" size="small" :loading="aborting" @click="void handleAbort()">
        {{ t("repo.abortOperation") }}
      </Button>
    </template>
  </Alert>
</template>
