// src/components/ScrollArea/src/ScrollArea.vue
<script setup lang="ts">
import { ref } from "vue";

import { cn } from "@/lib/utils";

defineOptions({ name: "ScrollArea" });

/**
 * antdv-next 没有独立 Scrollbar。面板主滚动仍走这一层，
 * 避免业务里散落 overflow-auto（也方便以后换成虚拟列表）。
 */

withDefaults(
  defineProps<{
    orientation?: "vertical" | "horizontal" | "both";
  }>(),
  { orientation: "vertical" },
);

const viewport = ref<HTMLElement | null>(null);
defineExpose({ viewport });
</script>

<template>
  <div class="relative min-h-0 min-w-0">
    <div
      ref="viewport"
      data-slot="scroll-area-viewport"
      :class="
        cn(
          'h-full w-full',
          orientation === 'horizontal' && 'overflow-x-auto overflow-y-hidden',
          orientation === 'vertical' && 'overflow-y-auto overflow-x-hidden',
          orientation === 'both' && 'overflow-auto',
        )
      "
    >
      <slot />
    </div>
  </div>
</template>

// src/components/ui/scroll-area.tsx
import * as React from "react";
import * as ScrollAreaPrimitive from "@radix-ui/react-scroll-area";

import { cn } from "@/lib/utils";

const ScrollArea = React.forwardRef<
  React.ElementRef<typeof ScrollAreaPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ScrollAreaPrimitive.Root>
>(({ className, children, ...props }, ref) => (
  <ScrollAreaPrimitive.Root
    ref={ref}
    className={cn("relative overflow-hidden", className)}
    {...props}
  >
    {/* max-h-[inherit]：父级仅设 max-h 时 viewport 也能正确限高并可滚动 */}
    <ScrollAreaPrimitive.Viewport className="h-full max-h-[inherit] w-full rounded-[inherit] [&>div]:!block [&>div]:!min-w-0">
      {children}
    </ScrollAreaPrimitive.Viewport>
    <ScrollBar />
    <ScrollAreaPrimitive.Corner />
  </ScrollAreaPrimitive.Root>
));
ScrollArea.displayName = ScrollAreaPrimitive.Root.displayName;

const ScrollBar = React.forwardRef<
  React.ElementRef<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>,
  React.ComponentPropsWithoutRef<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>
>(({ className, orientation = "vertical", ...props }, ref) => (
  <ScrollAreaPrimitive.ScrollAreaScrollbar
    ref={ref}
    orientation={orientation}
    className={cn(
      "flex touch-none transition-colors select-none",
      orientation === "vertical" &&
        "h-full w-2.5 border-l border-l-transparent p-px",
      orientation === "horizontal" &&
        "h-2.5 flex-col border-t border-t-transparent p-px",
      className,
    )}
    {...props}
  >
    <ScrollAreaPrimitive.ScrollAreaThumb className="bg-border relative flex-1 rounded-full" />
  </ScrollAreaPrimitive.ScrollAreaScrollbar>
));
ScrollBar.displayName = ScrollAreaPrimitive.ScrollAreaScrollbar.displayName;

export { ScrollArea, ScrollBar };
