// src/components/ai/AgentMessageItem.tsx
import dayjs from "dayjs";
import { LoaderCircle } from "lucide-react";
import { useTranslation } from "react-i18next";

import { AgentMessageCopyButton } from "@/components/ai/AgentMessageCopyButton";
import {
  AgentRichMessage,
  parseAgentMessage,
  type CompareBranchesAction,
} from "@/components/ai/AgentRichMessage";
import { cn } from "@/lib/utils";
import type { AgentChatMessage } from "@/types/ai";

interface AgentMessageItemProps {
  message: AgentChatMessage;
  onCompareBranches: (action: CompareBranchesAction) => void;
}

/** 当天只显示时分秒，跨天带上日期 */
function formatMessageTime(iso: string): string {
  const time = dayjs(iso);
  if (!time.isValid()) {
    return "";
  }
  if (time.isSame(dayjs(), "day")) {
    return time.format("HH:mm:ss");
  }
  return time.format("YYYY-MM-DD HH:mm:ss");
}

/** 单条消息气泡：内容 / 流式态 / 时间 / 复制 */
export function AgentMessageItem({ message, onCompareBranches }: AgentMessageItemProps) {
  const { t } = useTranslation();
  const isUser = message.role === "user";

  return (
    <div className={cn("flex flex-col gap-1", isUser ? "items-end" : "items-start")}>
      <div
        className={cn(
          "w-fit max-w-[88%] wrap-break-word rounded-lg px-3 py-2 text-xs leading-relaxed",
          isUser
            ? "bg-primary text-primary-foreground whitespace-pre-wrap"
            : "bg-muted text-foreground whitespace-normal",
        )}
      >
        {message.content ? (
          <AgentRichMessage
            {...parseAgentMessage(message.content)}
            onCompareBranches={onCompareBranches}
          />
        ) : null}
        {message.isStreaming ? (
          message.content ? (
            // 流式出字：末尾光标，避免转圈抢注意力
            <span
              className="bg-foreground ml-0.5 inline-block h-3 w-0.5 animate-pulse align-middle"
              aria-hidden="true"
            />
          ) : (
            <span className="inline-flex items-center gap-1.5">
              <LoaderCircle className="size-3 animate-spin" aria-hidden="true" />
              <span>{t("agent.thinking")}</span>
            </span>
          )
        ) : null}
      </div>
      {!message.isStreaming && message.content.trim() ? (
        <div className="flex items-center gap-1.5 px-0.5">
          <time
            className="text-muted-foreground text-xs leading-none tabular-nums"
            dateTime={message.createdAt}
          >
            {formatMessageTime(message.createdAt)}
          </time>
          <AgentMessageCopyButton content={message.content} />
        </div>
      ) : null}
    </div>
  );
}

// src/components/Ai/src/AgentMessageItem.vue
<script setup lang="ts">
import dayjs from "dayjs";
import { Button, Tooltip, message as antdMessage } from "antdv-next";
import { useI18n } from "vue-i18n";

import AgentReasoningBlock from "./AgentReasoningBlock.vue";
import { Icon } from "@/components/Icon";
import { cn } from "@/lib/utils";
import { toUserMessage } from "@/types/error";
import type { AgentChatMessage } from "@/types/ai";
import { copyToClipboard } from "@/utils/clipboard";

defineOptions({ name: "AgentMessageItem" });

const props = withDefaults(
  defineProps<{
    message: AgentChatMessage;
    actionsDisabled?: boolean;
  }>(),
  { actionsDisabled: false },
);

const { t } = useI18n();
const isUser = () => props.message.role === "user";

function formatMessageTime(iso: string): string {
  const time = dayjs(iso);
  if (!time.isValid()) {
    return "";
  }
  if (time.isSame(dayjs(), "day")) {
    return time.format("HH:mm:ss");
  }
  return time.format("YYYY-MM-DD HH:mm:ss");
}

const showFooter = () =>
  !props.message.isStreaming &&
  (Boolean(props.message.content.trim()) || Boolean(props.message.reasoningContent?.trim()));

async function handleCopy(): Promise<void> {
  const text = props.message.content.trim() || props.message.reasoningContent?.trim() || "";
  if (!text) {
    return;
  }
  try {
    await copyToClipboard(text);
    antdMessage.success(t("agent.copySuccess"));
  } catch (error) {
    antdMessage.error(toUserMessage(error) || t("agent.copyFailed"));
  }
}
</script>

<template>
  <div :class="cn('flex flex-col gap-1', isUser() ? 'items-end' : 'items-start')">
    <div
      :class="
        cn(
          'w-fit max-w-[88%] wrap-break-word rounded-lg px-3 py-2 text-xs leading-relaxed whitespace-pre-wrap',
          isUser() ? 'bg-primary text-primary-foreground' : 'bg-muted text-foreground',
        )
      "
    >
      <AgentReasoningBlock
        v-if="!isUser() && message.reasoningContent"
        :reasoning="message.reasoningContent"
        :is-streaming="Boolean(message.isStreaming)"
        :has-answer="Boolean(message.content.trim())"
        :duration-ms="message.reasoningDurationMs"
      />
      <template v-if="message.content">{{ message.content }}</template>
      <span
        v-if="message.isStreaming && message.content"
        class="bg-foreground ml-0.5 inline-block h-3 w-px animate-pulse"
        aria-hidden="true"
      />
      <span
        v-if="message.isStreaming && !message.content && !message.reasoningContent"
        class="inline-flex items-center gap-1.5"
      >
        <Icon name="LoaderCircle" :size="12" class="animate-spin" />
        <span>{{ t("agent.thinking") }}</span>
      </span>
    </div>
    <div
      v-if="showFooter()"
      :class="cn('flex items-center gap-1.5 px-0.5', isUser() ? 'flex-row-reverse' : 'flex-row')"
    >
      <time
        class="text-muted-foreground text-xs leading-none tabular-nums"
        :datetime="message.createdAt"
      >
        {{ formatMessageTime(message.createdAt) }}
      </time>
      <Tooltip :title="t('agent.copy')">
        <Button
          type="text"
          size="small"
          class="h-6 w-6 min-w-6 p-0"
          :disabled="actionsDisabled"
          :aria-label="t('agent.copy')"
          @click="void handleCopy()"
        >
          <Icon name="Copy" :size="12" />
        </Button>
      </Tooltip>
    </div>
  </div>
</template>
